const fs = require('fs');

fs.mkdirSync('dist', { recursive: true });
let h = fs.readFileSync('index.html', 'utf8');

// Self tab refinements.
h = h.replace(/\.authors \.author-row\{[^}]*\}/, ".authors .author-row{display:grid;grid-template-columns:32px minmax(0,1fr) 100px;gap:18px;align-items:center;border-bottom:1px solid var(--ruleSoft);padding:20px 0;text-align:left}");
h = h.replace(/\.aname\{[^}]*\}/, ".aname{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding-right:8px;font-family:var(--serif);font-style:italic;font-size:22px}");
h = h.replace(/\.count\{[^}]*\}/, ".count{justify-self:end;border:1px solid var(--ruleSoft);border-radius:999px;padding:7px 10px;white-space:nowrap;text-align:right;font-family:var(--mono);font-size:8px;letter-spacing:.12em;text-transform:uppercase;color:var(--warm)}");
h = h.replace(/\.settings\{[^}]*\}/, ".settings{width:40px;height:40px;border:1px solid var(--ruleSoft);border-radius:50%;background:rgba(247,243,235,.35);font-family:var(--serif);font-size:28px;font-style:normal;line-height:1;color:rgba(26,23,20,.75);transition:transform .18s ease}");
h = h.replace('onclick=\"openSettings()\">⚙</button>', 'onclick=\"openSettings()\">+</button>');
h = h.replace(/<button class=\"close\" onclick=\"closeSettings\(\)\">×<\/button>/, '<button class=\"close\" onclick=\"closeSettings()\">+</button>');
h = h.replace(/\.close\{[^}]*\}/, ".close{width:40px;height:40px;border-radius:50%;border:1px solid var(--rule);font-size:28px;line-height:1;transform:rotate(45deg)}");
h = h.replace(/\.sheet h2\{[^}]*\}/, ".sheet h2{font-family:var(--sans);font-weight:500;font-style:normal;font-size:30px;letter-spacing:-.035em;margin:8px 0 0}");
h = h.replace(/\.sheet\.on\{display:block\}/, ".sheet.on{display:block}.sheet .section{margin-top:30px;padding-top:24px}");
h = h.replace(/\.field\{[^}]*\}/, ".field{display:block;border-bottom:1px solid var(--ruleSoft);padding-bottom:10px;margin-top:16px}");
h = h.replace(/\.btns\{[^}]*\}/, ".btns{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px}");
h = h.replace(/\.pill\{[^}]*\}/, ".pill{border:1px solid var(--rule);border-radius:999px;padding:12px 14px;font-family:var(--mono);font-size:9px;text-transform:uppercase;letter-spacing:.16em}");
h = h.replace('Default avatar uses the first letter of your nickname. Photo upload is disabled in beta to keep the account system simple.', 'Avatar uses your nickname initial. Photo upload is disabled in beta.');
h = h.replace('Sharper is currently in beta. This version records a real local streak and minute count on this device. The full version is coming soon with cloud sync, account history, permanent archive, and paid subscription options.', 'Sharper is in beta. This preview records local streak and minutes on this device. Full version coming soon with cloud sync, account history, archive, and subscription options.');

// Top alignment and language.
h = h.replace(/\.top-progress\{[^}]*\}/, ".top-progress{position:sticky;top:40px;z-index:20;margin:0 28px;border:1px solid var(--ruleSoft);border-radius:999px;background:rgba(239,234,224,.86);backdrop-filter:blur(14px);padding:12px 20px}");
h = h.replace(/\.lib-head\{[^}]*\}/, ".lib-head{display:none}");
h = h.replace('Today’s voices', 'Daily specimens');
h = h.replace('<div class=\"lib-head\"><span>✶</span><div class=\"kicker ink\">Four domains, one mind</div>', '<div class=\"lib-head\"><span>✶</span><div class=\"kicker ink\">4 domains, 1 mind</div>');
h = h.replace('<div class=\"lib-head\"><span class=\"brand\"><i>✦</i>Sharper</span><div class=\"rule\"></div><div class=\"counter\">4 domains, 1 mind</div>', '<div class=\"lib-head\"><span>✶</span><div class=\"kicker ink\">4 domains, 1 mind</div>');

// Library tab refinements.
h = h.replace(/\.search input\{[^}]*\}/, ".search input{width:100%;border:0;outline:0;background:transparent;font-family:var(--mono);font-size:10px!important;letter-spacing:.14em;text-transform:uppercase;color:var(--warm)}");
h = h.replace(/\.filters\{[^}]*\}/, ".filters{display:flex;align-items:center;justify-content:flex-start;gap:18px;margin-top:22px;border-top:1px solid var(--ruleSoft);border-bottom:1px solid var(--ruleSoft);padding:12px 0 8px;overflow:visible;text-align:left}");
h = h.replace(/\.filters button,\.saved-toggle\{[^}]*\}/, ".filters button,.saved-toggle{font-family:var(--mono);font-size:10px;text-transform:uppercase;letter-spacing:.14em;color:var(--warm)}.filters button{width:auto;flex:0 0 auto;font-size:10px;letter-spacing:.14em;text-align:left;white-space:nowrap;color:rgba(26,23,20,.58);padding:0 0 5px;border-bottom:1px solid transparent}");
h = h.replace(/\.saved-toggle\{[^}]*\}/, ".saved-toggle{display:inline-flex;align-items:center;justify-content:flex-start;gap:8px;margin:0;padding:0 0 5px;font-size:10px!important;letter-spacing:.14em!important;color:rgba(26,23,20,.58)!important;border-bottom:1px solid transparent;text-align:left}");
h = h.replace('</style>', ".library-note{margin-top:18px;max-width:310px;font-family:var(--serif);font-style:italic;font-size:16px;line-height:1.45;color:var(--warm)}.filter-actions{display:flex;align-items:center;justify-content:flex-start;gap:24px;margin-top:8px;text-align:left}.filter-actions .saved-toggle.on{color:var(--earth)!important;border-bottom-color:var(--earth)}.library{padding-top:calc(32px + env(safe-area-inset-top))}.library .search{margin-top:0}.library .filters button,.library .saved-toggle{font-family:var(--mono)!important;font-size:10px!important;letter-spacing:.14em!important;text-transform:uppercase!important;line-height:1.2!important}.library .filters button.on{color:var(--earth)!important;border-bottom-color:var(--earth)}.reader-section:first-of-type{padding-bottom:36px}.reader-section:first-of-type p{font-size:22px;line-height:1.62;margin:22px 0}.reader-section:first-of-type p:last-child{margin-bottom:0}</style>");
h = h.replace("['leadership','Leadership','△']", "['leadership','Lead','△']");
h = h.replace("['communication','Communication','( )']", "['communication','Speak','( )']");
h = h.replace("<button id=\"savedToggle\" class=\"saved-toggle\">♡ Show saved</button><div id=\"paths\"", "<div class=\"filter-actions\"><button id=\"savedToggle\" class=\"saved-toggle\">Show saved</button><button id=\"clearFilter\" class=\"saved-toggle\">Clear</button></div><p class=\"library-note\">An accumulation of daily specimens — saved, unsaved, sorted, and returned to.</p><div id=\"paths\"");
h = h.replace(/\$\{p\.m\} min · 3 actions/g, "${p.m} min · ${domainName(p.d)}");
h = h.replace("$('savedToggle').onclick=()=>{state.savedOnly=!state.savedOnly;persist();renderLibrary()};", "$('savedToggle').onclick=()=>{state.savedOnly=true;persist();renderLibrary()};$('clearFilter').onclick=()=>{state.savedOnly=false;state.filter='all';persist();renderLibrary()};");
h = h.replace("$('savedToggle').innerHTML=state.savedOnly?'♥ Saved only':'♡ Show saved';", "$('savedToggle').innerHTML='Show saved';$('savedToggle').classList.toggle('on',state.savedOnly);");
h = h.replace("domains.map(d=>`<button", "domains.filter(d=>d[0]!=='all').map(d=>`<button");

// Reader tab: remove Reflection and give Dive deeper more room.
h = h.replace(/<div class='reader-section'><div class='kicker ink'>Reflection<\/div>[\s\S]*?<\/div><\/div>`;\$\('reader'\)\.classList\.add\('on'\);/, "`;$('reader').classList.add('on');");
h = h.replace(/<div class='reader-section'><div class='kicker ink'>Dive deeper<\/div>\$\{p\.read\.map\(x=>'<p>'\+x\+'<\/p>'\)\.join\(''\)\}<\/div>/, "<div class='reader-section'><div class='kicker ink'>Dive deeper</div>${p.read.map(x=>'<p>'+x+'</p>').join('')}<p>Carry this as a small test: notice where the idea appears in a real conversation, decision, or moment of resistance today.</p></div>");

// Daily content: three specimens per domain.
const extraPaths = ",{id:'decision-right-size',d:'leadership',t:'Right-Size the Decision',b:'Not every choice deserves the same amount of weight.',m:4,q:'The essence of strategy is choosing what not to do.',author:'Michael Porter',read:['A leader protects attention by sizing decisions correctly.','Ask whether this is reversible, consequential, or merely noisy.']},{id:'make-the-standard-visible',d:'leadership',t:'Make the Standard Visible',b:'Teams move faster when quality is no longer implicit.',m:4,q:'What gets measured gets managed.',author:'Peter Drucker',read:['A visible standard reduces interpretation tax.','Make the next good action obvious before you ask for speed.']},{id:'say-the-frame',d:'communication',t:'Say the Frame',b:'Before persuading, name the shape of the conversation.',m:3,q:'If you wish to converse with me, define your terms.',author:'Voltaire',read:['A frame tells people how to listen.','Open with purpose, boundary, and desired output.']},{id:'listen-for-the-missing-word',d:'communication',t:'Listen for the Missing Word',b:'What people omit often carries the real message.',m:4,q:'The most important thing in communication is hearing what is not said.',author:'Peter Drucker',read:['Absence is data. Notice what someone avoids naming.','The missing noun often reveals the hidden risk.']},{id:'reward-prediction',d:'psychology',t:'Reward Prediction Error',b:'Motivation spikes when reality beats expectation.',m:5,q:'The brain is a prediction machine.',author:'Andy Clark',read:['Dopamine is less about pleasure than update.','Use small unexpected wins to create momentum.']},{id:'attention-design',d:'psychology',t:'Design the Attention Field',b:'Your environment decides what becomes effortless.',m:4,q:'Attention is the beginning of devotion.',author:'Mary Oliver',read:['Attention is not only discipline. It is placement.','Move the desired action into the path of least resistance.']},{id:'amor-fati',d:'philosophy',t:'Amor Fati',b:'Use what happens as material, not interruption.',m:5,q:'My formula for greatness in a human being is amor fati.',author:'Friedrich Nietzsche · Ecce Homo',read:['This is not passive acceptance. It is conversion.','Ask how the obstacle can become part of the form.']},{id:'zhuangzi-usefulness',d:'philosophy',t:'The Use of Uselessness',b:'Some things survive because they refuse obvious utility.',m:5,q:'Everyone knows the use of the useful, but no one knows the use of the useless.',author:'Zhuangzi · 莊子',read:['Not all value announces itself as productivity.','Protect the margin where non-obvious thought can grow.']}";
h = h.replace(/\];const todayIds=\['open-the-room','manage-up','defaults','wu-wei'\]/, extraPaths + "];const todayIds=['open-the-room','art-of-recap','say-the-frame','manage-up','lead-without-loud','decision-right-size','defaults','reward-prediction','attention-design','wu-wei','amor-fati','zhuangzi-usefulness']");

// Today tab: local time based greeting.
h = h.replace(/\$\('snap'\)\.innerHTML=`<section class='today-page center'><div class='star'>✦<\/div><div class='kicker ink'>Today’s voices<\/div><h1>Good afternoon, \$\{state\.name\.split\(' '\)\[0\]\}\.<\/h1>/, "const hour=new Date().getHours();const greet=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening';$('snap').innerHTML=`<section class='today-page center'><div class='star'>✦</div><div class='kicker ink'>Daily specimens</div><h1>${greet}, ${state.name.split(' ')[0]}.</h1>");

fs.writeFileSync('dist/index.html', h);
