(function(){
  var names=['Aureus Socrates','Ludicus Seneca','Nebulosus Plato','Alatus Aristotle','Mellitus Marcus','Velutinus Cicero','Lunaris Epicurus','Sylvanus Heraclitus','Mirabilis Hypatia','Fabulosus Diogenes','Argenteus Plotinus','Serenus Spinoza','Curiosus Zeno','Nocturnus Nietzsche','Floridus Laozi','Ventulus Zhuangzi'];
  var astroLoc={lat:40.7128,lng:-74.0060};
  function slug(text){return text.toLowerCase().replace(/[^a-z0-9]+/g,'').slice(0,18)||'sharper'}
  function dayStamp(offset){var d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()+(offset||0));return d.toISOString().slice(0,10)}
  function currentGreeting(){var h=new Date().getHours();return h<12?'Good morning':h<18?'Good afternoon':'Good evening'}
  function pad(n){return String(n).padStart(2,'0')}
  function fmt(d){return pad(d.getHours())+':'+pad(d.getMinutes())}
  function rad(x){return x*Math.PI/180}
  function deg(x){return x*180/Math.PI}
  function sunTime(date,lat,lng,rise){var start=new Date(date);start.setHours(0,0,0,0);var N=Math.floor((start-new Date(start.getFullYear(),0,0))/86400000);var lngHour=lng/15;var t=N+((rise?6:18)-lngHour)/24;var M=(0.9856*t)-3.289;var L=M+(1.916*Math.sin(rad(M)))+(0.020*Math.sin(rad(2*M)))+282.634;L=(L+360)%360;var RA=deg(Math.atan(0.91764*Math.tan(rad(L))));RA=(RA+360)%360;RA+=(Math.floor(L/90)*90)-(Math.floor(RA/90)*90);RA/=15;var sinDec=0.39782*Math.sin(rad(L));var cosDec=Math.cos(Math.asin(sinDec));var cosH=(Math.cos(rad(90.833))-(sinDec*Math.sin(rad(lat))))/(cosDec*Math.cos(rad(lat)));if(cosH>1||cosH<-1)return null;var H=rise?360-deg(Math.acos(cosH)):deg(Math.acos(cosH));H/=15;var T=H+RA-(0.06571*t)-6.622;var UT=(T-lngHour+24)%24;var out=new Date(start);out.setUTCHours(Math.floor(UT),Math.round((UT%1)*60),0,0);return out}
  function moonPhase(date){var lp=2551443;var now=date.getTime()/1000;var newMoon=947182440;var phase=((now-newMoon)%lp)/lp;var names=['New moon','Waxing crescent','First quarter','Waxing gibbous','Full moon','Waning gibbous','Last quarter','Waning crescent'];return names[Math.floor((phase*8)+0.5)%8]}
  function applyGreeting(){var intro=document.querySelector('#snap .today-page.center h1');if(!intro)return;var first=(state.name||'Woopie').split(' ')[0];intro.innerHTML=currentGreeting()+',<br>'+first+'.'}
  function applyAstro(){var pages=document.querySelectorAll('#snap .today-page.center');var last=pages[pages.length-1];if(!last)return;var line=last.querySelector('.astro-line');if(!line){line=document.createElement('div');line.className='astro-line';last.appendChild(line)}var now=new Date(),sr=sunTime(now,astroLoc.lat,astroLoc.lng,true),ss=sunTime(now,astroLoc.lat,astroLoc.lng,false);line.innerHTML='Sunrise '+(sr?fmt(sr):'--:--')+' · Sunset '+(ss?fmt(ss):'--:--')+'<br>Moon · '+moonPhase(now)}
  function ensureUsage(){var today=dayStamp(0),yesterday=dayStamp(-1);var hadPriorState=!!localStorage.sharper_beta;if(!Array.isArray(state.activeDays)||!state.activeDays.length){state.activeDays=hadPriorState?[yesterday,today]:[today]}if(state.activeDays.indexOf(today)<0)state.activeDays.push(today);state.activeDays=Array.from(new Set(state.activeDays)).sort();saveRaw()}
  function saveRaw(){localStorage.sharper_beta=JSON.stringify(state)}
  function streakCount(){ensureUsage();var set={};state.activeDays.forEach(function(d){set[d]=true});var count=0,cursor=dayStamp(0);while(set[cursor]){count++;var d=new Date(cursor+'T00:00:00');d.setDate(d.getDate()-1);cursor=d.toISOString().slice(0,10)}return count||1}
  function enhanceSelf(){var identity=document.querySelector('.self .identity');if(!identity||document.getElementById('nameGen'))return;var button=document.createElement('button');button.id='nameGen';button.className='name-gen';button.type='button';button.textContent='Generate Latin name';button.onclick=function(){var next=names[Math.floor(Math.random()*names.length)];state.name=next;state.user=slug(next);save();renderSelf();applyGreeting()};identity.appendChild(button)}
  function enhanceStreakUI(){var streak=streakCount();var stat=document.getElementById('streakStat');if(stat)stat.textContent=streak;var lines=document.querySelectorAll('.streak-line');Array.prototype.slice.call(lines).forEach(function(line,i){line.textContent=i===0?'Streak · Day '+streak:'Streak · Day '+(streak+1)+' begins tomorrow'});var days=document.getElementById('days');if(days){var set={};state.activeDays.forEach(function(d){set[d]=true});days.innerHTML=Array.from({length:21},function(_,i){var offset=i-20;var date=dayStamp(offset);if(i===20)return '<span class="todaydot"><i class="dot done"></i></span>';return '<i class="dot '+(set[date]?'done':'')+'"></i>'}).join('')}applyGreeting();applyAstro()}
  function scrollTabTop(id){requestAnimationFrame(function(){var view=document.getElementById(id);if(view)view.scrollTo({top:0,left:0,behavior:'auto'});if(id==='today'){var snap=document.getElementById('snap');if(snap)snap.scrollTo({top:0,left:0,behavior:'auto'});var count=document.getElementById('count');if(count)count.textContent='1/6';var bars=document.getElementById('bars');if(bars)Array.prototype.slice.call(bars.children).forEach(function(b,i){b.classList.toggle('active',i===0)});applyGreeting();applyAstro()}})}
  function installPullRefresh(){var phone=document.querySelector('.phone');if(!phone||document.getElementById('pullRefresh'))return;var indicator=document.createElement('div');indicator.id='pullRefresh';indicator.className='pull-refresh';indicator.innerHTML='<span class="pull-orb"></span><span class="pull-label"></span>';phone.appendChild(indicator);var label=indicator.querySelector('.pull-label');var startY=0,pull=0,armed=false,active=false,threshold=74,maxPull=118;function activeView(){return document.querySelector('.view.on')}function atTop(){var view=activeView();if(!view)return false;if(view.id==='today'){var snap=document.getElementById('snap');return !snap||snap.scrollTop<=0}return view.scrollTop<=0}function setPull(value){pull=Math.max(0,Math.min(maxPull,value));var lag=Math.round(pull*.38),contentLag=Math.round(Math.min(46,pull*.34));indicator.style.setProperty('--pullLag',lag+'px');indicator.style.setProperty('--contentLag',contentLag+'px');indicator.style.setProperty('--pullFill',Math.round(Math.min(8,pull/threshold*8))+'px');phone.style.setProperty('--contentLag',contentLag+'px');indicator.classList.toggle('on',pull>8);indicator.classList.toggle('ready',pull>=threshold);label.textContent=pull>8?(pull>=threshold?'Release to refresh':'Pull to refresh'):''}function resetSoon(done){phone.classList.add('pull-settle');phone.classList.remove('pull-active');setPull(0);setTimeout(function(){indicator.className='pull-refresh';label.textContent='';phone.classList.remove('pull-settle')},done?520:260)}function refreshFeedback(){indicator.className='pull-refresh on refreshing';label.textContent='Refreshing';phone.classList.add('pull-settle');phone.style.setProperty('--contentLag','28px');try{renderToday();renderLibrary();renderSelf();applyGreeting();applyAstro()}catch(e){}setTimeout(function(){indicator.className='pull-refresh on done';label.textContent='Updated'},460);setTimeout(function(){resetSoon(true)},860)}phone.addEventListener('touchstart',function(e){if(e.touches.length!==1)return;startY=e.touches[0].clientY;active=atTop();armed=false},{passive:true});phone.addEventListener('touchmove',function(e){if(!active||e.touches.length!==1)return;var dy=e.touches[0].clientY-startY;if(dy<=0){setPull(0);return}if(!atTop())return;armed=true;phone.classList.add('pull-active');phone.classList.remove('pull-settle');setPull(Math.pow(dy,.86)*1.12);if(dy>12)e.preventDefault()},{passive:false});phone.addEventListener('touchend',function(){if(!armed)return;var shouldRefresh=pull>=threshold;active=false;armed=false;if(shouldRefresh)refreshFeedback();else resetSoon(false)},{passive:true});phone.addEventListener('touchcancel',function(){active=false;armed=false;resetSoon(false)},{passive:true})}
  function installReaderOverride(){window.toggleOriginalQuote=function(){var q=document.getElementById('readerQuote');if(!q)return;var on=q.dataset.origOn==='1';q.dataset.origOn=on?'0':'1';q.textContent='"'+(on?q.dataset.en:q.dataset.orig)+'"';q.classList.toggle('orig-on',!on)};openReader=function(id){window.current=id;var p=path(id);$('rmeta').textContent=domainName(p.d)+' · '+p.m+' min';$('rheart').textContent=isSaved(id)?'♥':'♡';var orig=p.orig?'<button class="orig-btn" onclick="toggleOriginalQuote()">Original</button>':'';var context=p.context?'<div class="specimen-context"><div class="label">Historical context</div><p>'+p.context+'</p></div>':'';var lesson=p.lesson?'<div class="reader-section"><div class="kicker ink">What it teaches</div><p>'+p.lesson+'</p></div>':'';var deploy=p.move?'<div class="deploy-block"><div class="label">Deploy today</div><p>'+p.move+'</p></div>':'';$('readerBody').innerHTML='<div class="kicker">Specimen</div><h1 class="'+(id==='manage-up'?'compact-title':'')+'">'+p.t+'</h1><p class="lead">'+p.b+'</p><div class="rq"><blockquote id="readerQuote" data-en="'+p.q.replace(/"/g,'&quot;')+'" data-orig="'+(p.orig||'').replace(/"/g,'&quot;')+'" data-orig-on="0">"'+p.q+'"</blockquote><div class="author">'+p.author+'</div>'+orig+'</div>'+context+lesson+deploy;$('reader').classList.add('on')}}
  ensureUsage();var baseRenderSelf=renderSelf;renderSelf=function(){baseRenderSelf();enhanceSelf();enhanceStreakUI();applyGreeting();applyAstro()};var baseRenderToday=renderToday;renderToday=function(){baseRenderToday();enhanceStreakUI();applyGreeting();applyAstro()};var baseTab=tab;tab=function(id){baseTab(id);var phone=document.querySelector('.phone');if(phone)phone.classList.toggle('self-mode',id==='self');scrollTabTop(id);enhanceStreakUI();applyGreeting();applyAstro()};installReaderOverride();renderToday();renderSelf();applyGreeting();applyAstro();installPullRefresh();if(navigator.geolocation){navigator.geolocation.getCurrentPosition(function(p){astroLoc={lat:p.coords.latitude,lng:p.coords.longitude};applyAstro()},function(){},{maximumAge:3600000,timeout:1600})}
  // force deploy hidden refresh label
})();