import { Quote } from './types';

export const quotes: Quote[] = [
  // Philosophy
  {
    id: 'q1',
    text: 'The unexamined life is not worth living.',
    author: 'Socrates',
    authorTitle: 'Greek Philosopher, 470–399 BC',
    category: 'philosophy',
    themes: ['self-knowledge', 'examined life', 'virtue'],
    archetypeAffinity: ['sage', 'mystic'],
  },
  {
    id: 'q2',
    text: 'You have power over your mind — not outside events. Realize this, and you will find strength.',
    author: 'Marcus Aurelius',
    authorTitle: 'Roman Emperor & Stoic Philosopher',
    category: 'philosophy',
    themes: ['stoicism', 'resilience', 'control'],
    archetypeAffinity: ['hero', 'sage'],
  },
  {
    id: 'q3',
    text: 'It is not that I am brave. It is that I know what matters.',
    author: 'Seneca',
    authorTitle: 'Roman Stoic Philosopher',
    category: 'philosophy',
    themes: ['courage', 'clarity', 'values'],
    archetypeAffinity: ['hero', 'sage'],
  },
  {
    id: 'q4',
    text: 'He who is everywhere is nowhere.',
    author: 'Seneca',
    authorTitle: 'Roman Stoic Philosopher',
    category: 'philosophy',
    themes: ['presence', 'focus', 'depth'],
    archetypeAffinity: ['sage', 'mystic'],
  },
  {
    id: 'q5',
    text: 'In the midst of winter, I found there was, within me, an invincible summer.',
    author: 'Albert Camus',
    authorTitle: 'French Philosopher & Nobel Laureate',
    category: 'philosophy',
    themes: ['resilience', 'inner strength', 'absurdism'],
    archetypeAffinity: ['rebel', 'hero'],
  },
  {
    id: 'q6',
    text: 'One must imagine Sisyphus happy.',
    author: 'Albert Camus',
    authorTitle: 'French Philosopher & Nobel Laureate',
    category: 'philosophy',
    themes: ['absurdism', 'meaning', 'joy'],
    archetypeAffinity: ['rebel', 'mystic'],
  },
  {
    id: 'q7',
    text: 'Without music, life would be a mistake.',
    author: 'Friedrich Nietzsche',
    authorTitle: 'German Philosopher',
    category: 'philosophy',
    themes: ['art', 'beauty', 'passion'],
    archetypeAffinity: ['creator', 'lover'],
  },
  {
    id: 'q8',
    text: 'We are what we repeatedly do. Excellence, then, is not an act but a habit.',
    author: 'Aristotle',
    authorTitle: 'Greek Philosopher, 384–322 BC',
    category: 'philosophy',
    themes: ['habit', 'excellence', 'virtue'],
    archetypeAffinity: ['hero', 'sage'],
  },
  {
    id: 'q9',
    text: 'The soul never thinks without an image.',
    author: 'Aristotle',
    authorTitle: 'Greek Philosopher, 384–322 BC',
    category: 'philosophy',
    themes: ['mind', 'imagination', 'perception'],
    archetypeAffinity: ['mystic', 'creator'],
  },
  {
    id: 'q10',
    text: 'At the touch of love, everyone becomes a poet.',
    author: 'Plato',
    authorTitle: 'Greek Philosopher, 428–348 BC',
    category: 'philosophy',
    themes: ['love', 'beauty', 'transformation'],
    archetypeAffinity: ['lover', 'creator'],
  },
  {
    id: 'q11',
    text: 'One is not born, but rather becomes, a woman.',
    author: 'Simone de Beauvoir',
    authorTitle: 'French Existentialist Philosopher',
    category: 'philosophy',
    themes: ['identity', 'freedom', 'becoming'],
    archetypeAffinity: ['rebel', 'explorer'],
  },
  {
    id: 'q12',
    text: 'I am awfully greedy; I want everything from life.',
    author: 'Simone de Beauvoir',
    authorTitle: 'French Existentialist Philosopher',
    category: 'philosophy',
    themes: ['desire', 'fullness', 'living'],
    archetypeAffinity: ['explorer', 'lover'],
  },
  {
    id: 'q13',
    text: 'Life can only be understood backwards; but it must be lived forwards.',
    author: 'Søren Kierkegaard',
    authorTitle: 'Danish Philosopher & Theologian',
    category: 'philosophy',
    themes: ['time', 'meaning', 'reflection'],
    archetypeAffinity: ['mystic', 'sage'],
  },
  {
    id: 'q14',
    text: 'The most common form of despair is not being who you are.',
    author: 'Søren Kierkegaard',
    authorTitle: 'Danish Philosopher & Theologian',
    category: 'philosophy',
    themes: ['authenticity', 'identity', 'despair'],
    archetypeAffinity: ['rebel', 'explorer'],
  },
  {
    id: 'q15',
    text: 'The limits of my language are the limits of my world.',
    author: 'Ludwig Wittgenstein',
    authorTitle: 'Austrian-British Philosopher',
    category: 'philosophy',
    themes: ['language', 'thought', 'perception'],
    archetypeAffinity: ['sage', 'creator'],
  },
  {
    id: 'q16',
    text: 'Make the best use of what is in your power, and take the rest as it happens.',
    author: 'Epictetus',
    authorTitle: 'Greek Stoic Philosopher',
    category: 'philosophy',
    themes: ['stoicism', 'acceptance', 'agency'],
    archetypeAffinity: ['hero', 'sage'],
  },
  {
    id: 'q17',
    text: 'To know oneself, one should assert oneself.',
    author: 'Albert Camus',
    authorTitle: 'French Philosopher & Nobel Laureate',
    category: 'philosophy',
    themes: ['self-knowledge', 'identity', 'action'],
    archetypeAffinity: ['rebel', 'hero'],
  },
  {
    id: 'q18',
    text: "We are condemned to be free.",
    author: 'Jean-Paul Sartre',
    authorTitle: 'French Existentialist Philosopher',
    category: 'philosophy',
    themes: ['freedom', 'responsibility', 'existence'],
    archetypeAffinity: ['rebel', 'explorer'],
  },
  // Psychology
  {
    id: 'q19',
    text: 'Who looks outside, dreams; who looks inside, awakes.',
    author: 'Carl Jung',
    authorTitle: 'Swiss Psychiatrist & Psychoanalyst',
    category: 'psychology',
    themes: ['self-knowledge', 'inner life', 'consciousness'],
    archetypeAffinity: ['mystic', 'sage'],
  },
  {
    id: 'q20',
    text: 'The privilege of a lifetime is to become who you truly are.',
    author: 'Carl Jung',
    authorTitle: 'Swiss Psychiatrist & Psychoanalyst',
    category: 'psychology',
    themes: ['individuation', 'authenticity', 'becoming'],
    archetypeAffinity: ['explorer', 'mystic'],
  },
  {
    id: 'q21',
    text: 'Everything that irritates us about others can lead us to an understanding of ourselves.',
    author: 'Carl Jung',
    authorTitle: 'Swiss Psychiatrist & Psychoanalyst',
    category: 'psychology',
    themes: ['shadow', 'projection', 'self-knowledge'],
    archetypeAffinity: ['sage', 'mystic'],
  },
  {
    id: 'q22',
    text: 'When we are no longer able to change a situation, we are challenged to change ourselves.',
    author: 'Viktor Frankl',
    authorTitle: 'Austrian Psychiatrist & Holocaust Survivor',
    category: 'psychology',
    themes: ['resilience', 'meaning', 'transformation'],
    archetypeAffinity: ['hero', 'sage'],
  },
  {
    id: 'q23',
    text: 'Between stimulus and response there is a space. In that space is our power to choose our response.',
    author: 'Viktor Frankl',
    authorTitle: 'Austrian Psychiatrist & Holocaust Survivor',
    category: 'psychology',
    themes: ['freedom', 'consciousness', 'agency'],
    archetypeAffinity: ['sage', 'hero'],
  },
  {
    id: 'q24',
    text: "Those who have a 'why' to live, can bear with almost any 'how'.",
    author: 'Viktor Frankl',
    authorTitle: 'Austrian Psychiatrist & Holocaust Survivor',
    category: 'psychology',
    themes: ['meaning', 'purpose', 'resilience'],
    archetypeAffinity: ['hero', 'mystic'],
  },
  {
    id: 'q25',
    text: 'Act as if what you do makes a difference. It does.',
    author: 'William James',
    authorTitle: 'American Philosopher & Psychologist',
    category: 'psychology',
    themes: ['agency', 'meaning', 'action'],
    archetypeAffinity: ['hero', 'caregiver'],
  },
  {
    id: 'q26',
    text: 'The task we must set for ourselves is not to feel secure, but to be able to tolerate insecurity.',
    author: 'Erich Fromm',
    authorTitle: 'German Social Psychologist & Philosopher',
    category: 'psychology',
    themes: ['courage', 'growth', 'freedom'],
    archetypeAffinity: ['explorer', 'hero'],
  },
  {
    id: 'q27',
    text: 'Love is not primarily a relationship to a specific person; it is an attitude, an orientation of character.',
    author: 'Erich Fromm',
    authorTitle: 'German Social Psychologist & Philosopher',
    category: 'psychology',
    themes: ['love', 'character', 'orientation'],
    archetypeAffinity: ['lover', 'caregiver'],
  },
  {
    id: 'q28',
    text: 'The good life is a process, not a state of being.',
    author: 'Carl Rogers',
    authorTitle: 'American Psychologist',
    category: 'psychology',
    themes: ['growth', 'becoming', 'process'],
    archetypeAffinity: ['explorer', 'creator'],
  },
  {
    id: 'q29',
    text: 'Vulnerability is not winning or losing; it is having the courage to show up and be seen.',
    author: 'Brené Brown',
    authorTitle: 'Research Professor & Author',
    category: 'psychology',
    themes: ['vulnerability', 'courage', 'authenticity'],
    archetypeAffinity: ['lover', 'hero'],
  },
  // Art & Literature
  {
    id: 'q30',
    text: 'I never painted dreams. I painted my own reality.',
    author: 'Frida Kahlo',
    authorTitle: 'Mexican Painter',
    category: 'art',
    themes: ['authenticity', 'reality', 'creation'],
    archetypeAffinity: ['creator', 'rebel'],
  },
  {
    id: 'q31',
    text: 'Feet, what do I need you for when I have wings to fly?',
    author: 'Frida Kahlo',
    authorTitle: 'Mexican Painter',
    category: 'art',
    themes: ['freedom', 'transcendence', 'spirit'],
    archetypeAffinity: ['explorer', 'rebel'],
  },
  {
    id: 'q32',
    text: 'You cannot find peace by avoiding life.',
    author: 'Virginia Woolf',
    authorTitle: 'English Writer & Modernist',
    category: 'literature',
    themes: ['courage', 'engagement', 'living'],
    archetypeAffinity: ['hero', 'explorer'],
  },
  {
    id: 'q33',
    text: 'Not everything that is faced can be changed, but nothing can be changed until it is faced.',
    author: 'James Baldwin',
    authorTitle: 'American Novelist & Activist',
    category: 'literature',
    themes: ['truth', 'courage', 'change'],
    archetypeAffinity: ['rebel', 'sage'],
  },
  {
    id: 'q34',
    text: 'If you have some power, then your job is to empower somebody else.',
    author: 'Toni Morrison',
    authorTitle: 'American Nobel Laureate',
    category: 'literature',
    themes: ['power', 'responsibility', 'care'],
    archetypeAffinity: ['caregiver', 'rebel'],
  },
  {
    id: 'q35',
    text: 'I live my life in widening circles that reach out across the world.',
    author: 'Rainer Maria Rilke',
    authorTitle: 'Bohemian-Austrian Poet',
    category: 'literature',
    themes: ['expansion', 'growth', 'connection'],
    archetypeAffinity: ['explorer', 'mystic'],
  },
  {
    id: 'q36',
    text: 'Be patient toward all that is unsolved in your heart and try to love the questions themselves.',
    author: 'Rainer Maria Rilke',
    authorTitle: 'Bohemian-Austrian Poet',
    category: 'literature',
    themes: ['patience', 'uncertainty', 'becoming'],
    archetypeAffinity: ['sage', 'mystic'],
  },
  {
    id: 'q37',
    text: 'Perhaps all the dragons in our lives are princesses who are only waiting to see us act, just once, with beauty and courage.',
    author: 'Rainer Maria Rilke',
    authorTitle: 'Bohemian-Austrian Poet',
    category: 'literature',
    themes: ['courage', 'transformation', 'shadow'],
    archetypeAffinity: ['hero', 'mystic'],
  },
  {
    id: 'q38',
    text: 'I found I could say things with color and shapes that I could not say any other way — things I had no words for.',
    author: 'Georgia O\'Keeffe',
    authorTitle: 'American Modernist Painter',
    category: 'art',
    themes: ['expression', 'language', 'creation'],
    archetypeAffinity: ['creator', 'mystic'],
  },
  {
    id: 'q39',
    text: 'The function of art is to do more than tell it like it is — it is to imagine what is possible.',
    author: 'bell hooks',
    authorTitle: 'American Author & Cultural Critic',
    category: 'art',
    themes: ['imagination', 'possibility', 'transformation'],
    archetypeAffinity: ['creator', 'rebel'],
  },
  {
    id: 'q40',
    text: 'Love is an action, never simply a feeling.',
    author: 'bell hooks',
    authorTitle: 'American Author & Cultural Critic',
    category: 'literature',
    themes: ['love', 'action', 'commitment'],
    archetypeAffinity: ['lover', 'caregiver'],
  },
  // Architecture
  {
    id: 'q41',
    text: 'I want people to feel the silence, to feel the power of architecture.',
    author: 'Tadao Ando',
    authorTitle: 'Japanese Architect, Pritzker Prize Laureate',
    category: 'architecture',
    themes: ['silence', 'presence', 'power'],
    archetypeAffinity: ['mystic', 'creator'],
  },
  {
    id: 'q42',
    text: 'My goal is to simplify complexity and to make the complex simple.',
    author: 'Tadao Ando',
    authorTitle: 'Japanese Architect, Pritzker Prize Laureate',
    category: 'architecture',
    themes: ['simplicity', 'clarity', 'craft'],
    archetypeAffinity: ['sage', 'creator'],
  },
  {
    id: 'q43',
    text: 'The sun never knew how great it was until it hit the side of a building.',
    author: 'Louis Kahn',
    authorTitle: 'American Architect',
    category: 'architecture',
    themes: ['light', 'revelation', 'beauty'],
    archetypeAffinity: ['creator', 'mystic'],
  },
  {
    id: 'q44',
    text: 'A great building must begin with the unmeasurable, pass through measurable means, and in the end must be unmeasurable.',
    author: 'Louis Kahn',
    authorTitle: 'American Architect',
    category: 'architecture',
    themes: ['mystery', 'craft', 'transcendence'],
    archetypeAffinity: ['mystic', 'creator'],
  },
  {
    id: 'q45',
    text: 'There are 360 degrees, so why stick to one?',
    author: 'Zaha Hadid',
    authorTitle: 'Iraqi-British Architect, Pritzker Prize Laureate',
    category: 'architecture',
    themes: ['possibility', 'freedom', 'vision'],
    archetypeAffinity: ['creator', 'rebel'],
  },
  {
    id: 'q46',
    text: 'Architecture is really about well-being. I think that people want to feel good in a space.',
    author: 'Zaha Hadid',
    authorTitle: 'Iraqi-British Architect, Pritzker Prize Laureate',
    category: 'architecture',
    themes: ['care', 'humanity', 'space'],
    archetypeAffinity: ['caregiver', 'creator'],
  },
  {
    id: 'q47',
    text: 'Less is more.',
    author: 'Mies van der Rohe',
    authorTitle: 'German-American Architect',
    category: 'architecture',
    themes: ['simplicity', 'restraint', 'elegance'],
    archetypeAffinity: ['sage', 'creator'],
  },
  {
    id: 'q48',
    text: 'The thing always happens that you really believe in; and the belief in a thing makes it happen.',
    author: 'Frank Lloyd Wright',
    authorTitle: 'American Architect',
    category: 'architecture',
    themes: ['belief', 'will', 'creation'],
    archetypeAffinity: ['creator', 'hero'],
  },
  // Spirituality & Wisdom
  {
    id: 'q49',
    text: 'Out beyond ideas of wrongdoing and rightdoing, there is a field. I\'ll meet you there.',
    author: 'Rumi',
    authorTitle: '13th-Century Persian Poet & Sufi Mystic',
    category: 'literature',
    themes: ['transcendence', 'unity', 'love'],
    archetypeAffinity: ['mystic', 'lover'],
  },
  {
    id: 'q50',
    text: 'You were born with wings. Why prefer to crawl through life?',
    author: 'Rumi',
    authorTitle: '13th-Century Persian Poet & Sufi Mystic',
    category: 'literature',
    themes: ['potential', 'freedom', 'flight'],
    archetypeAffinity: ['explorer', 'hero'],
  },
  {
    id: 'q51',
    text: 'Nature does not hurry, yet everything is accomplished.',
    author: 'Lao Tzu',
    authorTitle: 'Ancient Chinese Philosopher, Tao Te Ching',
    category: 'philosophy',
    themes: ['patience', 'flow', 'naturalness'],
    archetypeAffinity: ['mystic', 'sage'],
  },
  {
    id: 'q52',
    text: 'Knowing others is intelligence; knowing yourself is true wisdom.',
    author: 'Lao Tzu',
    authorTitle: 'Ancient Chinese Philosopher, Tao Te Ching',
    category: 'philosophy',
    themes: ['self-knowledge', 'wisdom', 'mastery'],
    archetypeAffinity: ['sage', 'mystic'],
  },
  {
    id: 'q53',
    text: 'Attention is the rarest and purest form of generosity.',
    author: 'Simone Weil',
    authorTitle: 'French Philosopher & Mystic',
    category: 'philosophy',
    themes: ['attention', 'love', 'presence'],
    archetypeAffinity: ['caregiver', 'sage'],
  },
  {
    id: 'q54',
    text: 'The most beautiful thing we can experience is the mysterious.',
    author: 'Albert Einstein',
    authorTitle: 'Theoretical Physicist',
    category: 'philosophy',
    themes: ['mystery', 'wonder', 'beauty'],
    archetypeAffinity: ['mystic', 'sage'],
  },
  {
    id: 'q55',
    text: 'I took a deep breath and listened to the old brag of my heart: I am, I am, I am.',
    author: 'Sylvia Plath',
    authorTitle: 'American Poet & Novelist',
    category: 'literature',
    themes: ['existence', 'identity', 'aliveness'],
    archetypeAffinity: ['rebel', 'mystic'],
  },
  {
    id: 'q56',
    text: 'The most courageous act is still to think for yourself. Aloud.',
    author: 'Coco Chanel',
    authorTitle: 'French Fashion Designer',
    category: 'art',
    themes: ['courage', 'independence', 'voice'],
    archetypeAffinity: ['rebel', 'creator'],
  },
  {
    id: 'q57',
    text: 'To exist is to change, to change is to mature, to mature is to go on creating oneself endlessly.',
    author: 'Henri Bergson',
    authorTitle: 'French Philosopher',
    category: 'philosophy',
    themes: ['change', 'growth', 'becoming'],
    archetypeAffinity: ['creator', 'explorer'],
  },
  {
    id: 'q58',
    text: 'A room without books is like a body without a soul.',
    author: 'Marcus Tullius Cicero',
    authorTitle: 'Roman Philosopher & Statesman',
    category: 'philosophy',
    themes: ['knowledge', 'books', 'soul'],
    archetypeAffinity: ['sage', 'creator'],
  },
  {
    id: 'q59',
    text: 'I am not afraid of storms, for I am learning how to sail my ship.',
    author: 'Louisa May Alcott',
    authorTitle: 'American Novelist',
    category: 'literature',
    themes: ['courage', 'learning', 'resilience'],
    archetypeAffinity: ['hero', 'explorer'],
  },
  {
    id: 'q60',
    text: 'The only journey is the journey within.',
    author: 'Rainer Maria Rilke',
    authorTitle: 'Bohemian-Austrian Poet',
    category: 'literature',
    themes: ['inner life', 'self-discovery', 'journey'],
    archetypeAffinity: ['mystic', 'sage'],
  },
];

export function getOrderedQuotes(archetypeId: string, viewedIds: string[]): Quote[] {
  const affinity = quotes.filter(
    (q) => q.archetypeAffinity.includes(archetypeId) && !viewedIds.includes(q.id)
  );
  const rest = quotes.filter(
    (q) => !q.archetypeAffinity.includes(archetypeId) && !viewedIds.includes(q.id)
  );
  const viewed = quotes.filter((q) => viewedIds.includes(q.id));

  return [...shuffle(affinity), ...shuffle(rest), ...shuffle(viewed)];
}

function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5);
}
