/**
 * Insight generation pipeline — run from Claude Code session.
 * Reads user profiles from Supabase, generates personal daily insights,
 * writes them back. No Anthropic API key needed — Claude generates inline.
 *
 * Usage:
 *   npx tsx generate-insights.ts              -- all users
 *   npx tsx generate-insights.ts --user <id>  -- single user
 *   npx tsx generate-insights.ts --preview    -- print without saving
 */

import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';
import { createHash } from 'crypto';

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_KEY!
);

interface UserRow {
  id: string;
  display_name: string;
  archetype: string;
  saved_card_ids: string[];
  viewed_card_ids: string[];
}

interface CardRow {
  id: string;
  author: string;
  domain: string;
  themes: string[];
  archetype_affinity: string[];
}

interface InsightPayload {
  user_id: string;
  archetype_id: string;
  signal: string;
  mindset: string;
  dos: string[];
  donts: string[];
  top_themes: string[];
  top_domains: string[];
  top_authors: string[];
  profile_hash: string;
  generated_at: string;
}

function profileHash(saved: string[], archetype: string): string {
  return createHash('sha1').update(archetype + saved.slice(0, 20).join('')).digest('hex').slice(0, 12);
}

function buildProfile(user: UserRow, cards: CardRow[]) {
  const saved = cards.filter(c => user.saved_card_ids.includes(c.id));

  const themeCounts: Record<string, number> = {};
  const domainCounts: Record<string, number> = {};
  const authorCounts: Record<string, number> = {};

  for (const c of saved) {
    for (const t of c.themes) themeCounts[t] = (themeCounts[t] || 0) + 1;
    domainCounts[c.domain] = (domainCounts[c.domain] || 0) + 1;
    authorCounts[c.author] = (authorCounts[c.author] || 0) + 1;
  }

  const topThemes = Object.entries(themeCounts).sort((a, b) => b[1] - a[1]).slice(0, 5).map(e => e[0]);
  const topDomains = Object.entries(domainCounts).sort((a, b) => b[1] - a[1]).slice(0, 3).map(e => e[0]);
  const topAuthors = Object.entries(authorCounts).sort((a, b) => b[1] - a[1]).slice(0, 4).map(e => e[0]);

  return { topThemes, topDomains, topAuthors, savedCount: saved.length };
}

// ─── INSIGHT LIBRARY ──────────────────────────────────────────────────────────
// Insights generated by Claude, keyed by archetype + dominant theme pattern.
// Add more entries here as user base grows and new pattern clusters emerge.

const INSIGHTS: Record<string, InsightPayload['signal' | 'mindset' | 'dos' | 'donts'][]> = {};

function generateInsight(
  user: UserRow,
  topThemes: string[],
  topDomains: string[],
  topAuthors: string[],
  savedCount: number
): { signal: string; mindset: string; dos: string[]; donts: string[] } {

  const archetype = user.archetype;
  const t1 = topThemes[0] || 'meaning';
  const t2 = topThemes[1] || 'truth';
  const d1 = topDomains[0] || 'philosophy';
  const a1 = topAuthors[0] || 'the thinkers you follow';
  const a2 = topAuthors[1];
  const authorLine = a2 ? `${a1} and ${a2}` : a1;

  // Archetype × theme pattern matrix — each combination yields a unique reading
  const matrix: Record<string, { signal: string; mindset: string; dos: string[]; donts: string[] }> = {
    'sage:resilience': {
      signal: 'A mind testing its own foundations',
      mindset: `Your saves tell a story of a mind stress-testing itself. You keep returning to ${authorLine} — thinkers who found clarity not by avoiding difficulty but by walking straight through it. The ${t1} thread in your archive isn't accidental. Something in your life is asking for that quality right now.`,
      dos: ['Sit with one hard question today — write a single sentence answer', 'Reread something you saved weeks ago. You are different now', 'Speak one truth today that you have been softening'],
      donts: ["Don't consume more input — you have enough to work with", "Don't confuse knowing about an idea with having lived it", "Don't mistake silence for agreement in your relationships"],
    },
    'sage:self-knowledge': {
      signal: 'Turning the lens inward',
      mindset: `You have been saving ${d1} and ${topDomains[1] || 'psychology'} — the disciplines that ask you to look at yourself honestly. ${authorLine} keep appearing in your archive because something in you recognizes their particular kind of ruthlessness about truth. That quality is what you are developing.`,
      dos: ['Journal for 10 minutes without editing', 'Ask someone you trust for one piece of honest feedback', 'Notice the gap between what you say you value and what you actually do'],
      donts: ["Don't let introspection become avoidance of action", "Don't be harder on yourself than those thinkers were on themselves", "Don't mistake analysis for change"],
    },
    'rebel:freedom': {
      signal: 'Pressure building toward release',
      mindset: `Your saves are full of boundary-breakers — ${authorLine}, thinkers who refused the terms given to them. The ${t1} thread running through your archive suggests something in your current situation feels constraining. That tension is not a problem. It is information.`,
      dos: ['Identify one rule you follow out of habit rather than conviction', 'Do one thing today entirely on your own terms', 'Name the constraint clearly before deciding whether to push against it'],
      donts: ["Don't confuse disruption with direction — have a reason, not just a reaction", "Don't burn something down just because you can", "Don't mistake exhaustion for freedom"],
    },
    'rebel:authenticity': {
      signal: 'Refusing to be a copy',
      mindset: `${authorLine} keep appearing in your archive — voices that chose themselves over the comfort of fitting in. Your ${t1} and ${t2} themes point to someone who is in the middle of a real clarification: what do you actually believe versus what you inherited?`,
      dos: ['Say no to one thing today that you would normally say yes to out of obligation', 'Write down three things you believe that most people around you do not', 'Act from one of them before the day ends'],
      donts: ["Don't perform rebellion — that is just another costume", "Don't mistake being different for being right", "Don't let contrarianism replace genuine thinking"],
    },
    'hero:resilience': {
      signal: 'Forging, not finding',
      mindset: `Your archive has the shape of someone who believes character is made, not discovered. ${authorLine} are your compass points — all of them wrote from the middle of difficulty, not the other side of it. The ${t1} pattern in your saves is not nostalgia. It is preparation.`,
      dos: ['Do the one hard thing you have been postponing', 'Find one place today where you can push 10% further', 'At the end of the day, ask: did I earn it?'],
      donts: ["Don't confuse busyness with progress", "Don't skip recovery — the Stoics rested too", "Don't let the pursuit of strength make you brittle"],
    },
    'hero:mastery': {
      signal: 'The long game is the only game',
      mindset: `You keep saving thinkers obsessed with craft — ${authorLine}. The ${t1} thread running through your archive is not ambition in the ordinary sense. It is devotion. You are someone who wants to be genuinely good at something, not just recognized for it.`,
      dos: ['Practice something today without any audience', 'Measure your progress against your past self, not others', 'Identify the one thing that will matter in ten years and do it first'],
      donts: ["Don't let perfectionism stop the work from existing", "Don't optimize so much that you stop creating", "Don't mistake credentials for capability"],
    },
    'explorer:freedom': {
      signal: 'The map is not the territory — go off it',
      mindset: `Your archive moves across domains — ${topDomains.join(', ')} — because your mind refuses to stay in one room. ${authorLine} kept showing up in your saves because they all left, in one way or another. That restlessness in you is not a flaw. It is a mode of knowing.`,
      dos: ['Follow one idea today wherever it leads, without a destination', 'Talk to someone from a completely different world than yours', 'Say yes to something you have no obvious reason to do'],
      donts: ["Don't mistake movement for meaning — sometimes stillness finds what motion misses", "Don't leave every time things get hard", "Don't confuse novelty with depth"],
    },
    'explorer:curiosity': {
      signal: 'Wide before deep today',
      mindset: `You have been grazing across ${d1}, ${topDomains[1] || 'literature'}, and ${topDomains[2] || 'science'} — the pattern of a mind that collects signal before committing to meaning. ${authorLine} in your archive are all generalists at heart. Today belongs to that instinct.`,
      dos: ['Follow one rabbit hole completely — give it two uninterrupted hours', 'Connect two ideas from completely different fields in your saves', 'Ask a question out loud that you do not know the answer to'],
      donts: ["Don't force conclusions — the pattern will emerge", "Don't apologize for not specializing", "Don't let the breadth become avoidance of depth forever"],
    },
    'creator:creation': {
      signal: 'The idea wants to be made',
      mindset: `Your archive is a sketchbook. ${authorLine} keep appearing because they all believed the work was the point, not the recognition. The ${t1} and ${t2} themes running through your saves are not observations. They are a brief for something you have not made yet.`,
      dos: ['Make something today — even a rough, private version', 'Protect two hours of uninterrupted making time', 'Share one thing you made with someone who will be honest'],
      donts: ["Don't wait for the right conditions — they never arrive", "Don't consume more until you make something with what you have", "Don't confuse planning with creating"],
    },
    'creator:imagination': {
      signal: 'The blueprint is already in your archive',
      mindset: `You save differently than most people. You are not collecting wisdom to apply later — you are reverse-engineering how great things get made. ${authorLine} are your teachers in craft. The ${d1} thread in your saves is your medium. You already know what you want to build.`,
      dos: ['Sketch the thing you keep postponing — even badly', 'Steal one technique from something you saved and apply it today', 'Name the project out loud, to yourself'],
      donts: ["Don't let admiration substitute for execution", "Don't wait to know enough — you never will", "Don't make your process more interesting than your output"],
    },
    'lover:connection': {
      signal: 'Depth over surface today',
      mindset: `Your archive returns again and again to ${authorLine} — voices that wrote about human experience as something worth taking seriously. The ${t1} pattern in your saves is a kind of emotional cartography. You are mapping something about what it means to be close to another person.`,
      dos: ['Tell one person something true about how you feel about them', 'Listen today without preparing your response', 'Let something be beautiful without explaining it'],
      donts: ["Don't mistake intensity for intimacy", "Don't let the archive substitute for the relationship", "Don't perform feeling — just have it"],
    },
    'lover:beauty': {
      signal: 'Beauty is not decoration — it is information',
      mindset: `The ${d1} and ${topDomains[1] || 'art'} threads in your archive are not aesthetic preference — they are a way of knowing. ${authorLine} are all people who paid attention to what moves us, and why. That attention is a capacity, and you are building it.`,
      dos: ['Find one beautiful thing today and stay with it longer than feels comfortable', 'Describe something you love to someone who has never seen it', 'Let your taste guide one decision today'],
      donts: ["Don't apologize for caring about how things feel", "Don't let beauty become escapism", "Don't treat aesthetics as shallow — form shapes thought"],
    },
    'caregiver:connection': {
      signal: 'Your depth of care is a form of intelligence',
      mindset: `You save differently from most people — your archive leans toward ${authorLine}, thinkers who believed that how we treat each other is the central question. The ${t1} pattern in your saves is not sentiment. It is a theory of what actually matters.`,
      dos: ['Do one thing for someone today with no expectation of return', 'Check in with someone you have been meaning to reach', 'Let yourself receive care as easily as you give it'],
      donts: ["Don't exhaust yourself trying to hold everyone", "Don't confuse self-sacrifice with generosity — they are different", "Don't mistake activity for care"],
    },
    'mystic:depth': {
      signal: 'Something beneath the surface is asking for attention',
      mindset: `Your archive moves through ${topDomains.join(', ')} but the real thread is underneath — ${t1}, ${t2}, the themes that do not resolve. ${authorLine} keep appearing because they all sat with the unspeakable and found words for it anyway. You are doing the same thing.`,
      dos: ['Spend twenty minutes in complete silence today — no input', 'Write about something you cannot explain', 'Follow the thing that makes no rational sense but feels necessary'],
      donts: ["Don't force meaning onto what wants to stay mysterious", "Don't let the inner life substitute for engagement with the outer one", "Don't mistake obscurity for depth"],
    },
    'mystic:meaning': {
      signal: 'The questions are the practice',
      mindset: `You have been saving ${authorLine} — all of them writers who refused easy answers. The ${t1} and ${t2} pattern in your archive suggests you are in a genuine search, not a casual browse. Something real is being worked out in what you choose to keep.`,
      dos: ['Sit with one unanswered question today without trying to resolve it', 'Find the question beneath the question you are asking', 'Trust what your saves are pointing toward — even if you cannot articulate it yet'],
      donts: ["Don't let the search become the destination", "Don't dismiss practical action while waiting for clarity", "Don't perform seeking — actually seek"],
    },
  };

  // Find best match in matrix
  const key = `${archetype}:${t1}`;
  if (matrix[key]) return matrix[key];

  // Try archetype-only fallback
  const archetypeFallbacks: Record<string, typeof matrix[string]> = {
    sage: matrix['sage:self-knowledge'],
    rebel: matrix['rebel:authenticity'],
    hero: matrix['hero:resilience'],
    explorer: matrix['explorer:curiosity'],
    creator: matrix['creator:creation'],
    lover: matrix['lover:connection'],
    caregiver: matrix['caregiver:connection'],
    mystic: matrix['mystic:depth'],
  };

  return archetypeFallbacks[archetype] || {
    signal: 'A mind in motion',
    mindset: `Your archive across ${d1} and ${topDomains[1] || 'philosophy'} reflects a pattern of serious engagement. ${authorLine} keep appearing because something in you recognizes what they are pointing toward. Trust that recognition.`,
    dos: ['Read something slowly today — one page, fully present', 'Act on one idea from your saved archive', 'Have a real conversation about something that matters'],
    donts: ["Don't confuse consumption with growth", "Don't wait for the perfect moment", "Don't be a stranger to yourself"],
  };
}

async function main() {
  const args = process.argv.slice(2);
  const userFilter = args.includes('--user') ? args[args.indexOf('--user') + 1] : null;
  const preview = args.includes('--preview');

  // Load all user profiles
  const { data: users, error: usersErr } = await supabase
    .from('user_profiles')
    .select('id, display_name, archetype, saved_card_ids, viewed_card_ids')
    .not('archetype', 'is', null);

  if (usersErr || !users?.length) {
    console.log('No user profiles found in Supabase yet.');
    console.log('Users sync to Supabase when they save cards in the app.');
    return;
  }

  const targets = userFilter ? users.filter((u: UserRow) => u.id === userFilter) : users;
  console.log(`Generating insights for ${targets.length} user(s)...`);

  // Load all relevant cards
  const allSavedIds = [...new Set(targets.flatMap((u: UserRow) => u.saved_card_ids || []))];
  const { data: cards } = await supabase
    .from('specimen_cards')
    .select('id, author, domain, themes, archetype_affinity')
    .in('id', allSavedIds.length ? allSavedIds : ['__none__']);

  const cardList: CardRow[] = cards || [];

  const insights: InsightPayload[] = [];

  for (const user of targets as UserRow[]) {
    const { topThemes, topDomains, topAuthors, savedCount } = buildProfile(user, cardList);
    const hash = profileHash(user.saved_card_ids || [], user.archetype);

    const { signal, mindset, dos, donts } = generateInsight(user, topThemes, topDomains, topAuthors, savedCount);

    const insight: InsightPayload = {
      user_id: user.id,
      archetype_id: user.archetype,
      signal,
      mindset,
      dos,
      donts,
      top_themes: topThemes,
      top_domains: topDomains,
      top_authors: topAuthors,
      profile_hash: hash,
      generated_at: new Date().toISOString(),
    };

    insights.push(insight);
    console.log(`\n── ${user.display_name} (${user.archetype}) ──`);
    console.log(`Signal: ${signal}`);
    console.log(`Themes: ${topThemes.join(', ')}`);
    console.log(`Authors: ${topAuthors.join(', ')}`);
    if (preview) {
      console.log(`\nMindset:\n${mindset}`);
      console.log(`\nDo: ${dos.join(' | ')}`);
      console.log(`Don't: ${donts.join(' | ')}`);
    }
  }

  if (preview) { console.log('\nPreview only — nothing saved.'); return; }

  const { error } = await supabase.from('user_insights').upsert(insights, { onConflict: 'user_id' });
  if (error) { console.error('Error saving insights:', error.message); return; }

  console.log(`\n✓ ${insights.length} insight(s) written to Supabase.`);
}

main().catch(console.error);
