/**
 * Context generation pipeline — run from Claude Code.
 * Writes historical_context, meaning, and why_it_matters for each active card.
 *
 * Usage:
 *   npx tsx generate-contexts.ts              -- all unloaded cards
 *   npx tsx generate-contexts.ts --reload     -- reload all cards
 *   npx tsx generate-contexts.ts --author "Rumi"  -- specific author
 */

import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_SERVICE_KEY!);

// ─── AUTHOR HISTORICAL CONTEXTS ───────────────────────────────────────────────

const AUTHOR_CONTEXT: Record<string, string> = {
  'Socrates': `Socrates (470–399 BC) never wrote a single word. Everything we know about him comes from his students, primarily Plato, who recorded his conversations after his death. He walked the streets of Athens engaging anyone willing to talk — craftsmen, politicians, poets — asking relentless questions about justice, courage, knowledge, and the good life. He called this method elenchus: the art of probing assumptions until they collapse. The Athenian establishment found him intolerable. In 399 BC, at age 70, he was tried for impiety and corrupting the youth, found guilty, and sentenced to death by hemlock. He refused to flee when given the chance, arguing that a life that abandoned its principles to survive was not worth living. His death became the founding myth of Western philosophy.`,

  'Plato': `Plato (428–348 BC) was 28 when his teacher Socrates was executed. The trauma shaped everything he wrote. He founded the Academy in Athens around 387 BC — one of the earliest institutions of higher learning in the Western world — and ran it for 40 years. His dialogues, written over five decades, use Socrates as a character to explore questions that had never been asked so systematically: What is justice? What is beauty? What is knowledge? What is the ideal form of society? Plato believed the physical world was a shadow of a higher realm of perfect Forms — that the chair you sit on is an imperfect copy of the Form of Chair. His influence on Western thought, theology, and science is incalculable. Alfred North Whitehead famously said that all of philosophy is footnotes to Plato.`,

  'Aristotle': `Aristotle (384–322 BC) was Plato's most brilliant student and his most determined critic. He studied at the Academy for 20 years, then left to tutor a 13-year-old named Alexander — who would become Alexander the Great. He later founded his own school, the Lyceum, and over his lifetime wrote or dictated treatises on biology, physics, metaphysics, logic, rhetoric, ethics, politics, theater, and poetry. He invented the formal study of logic, described 500 species of animals, and laid the foundation for empirical science. Where Plato looked upward to abstract Forms, Aristotle looked at the world directly: observe, classify, reason from evidence. His Nicomachean Ethics, written as a set of lecture notes, remains one of the most read works in moral philosophy 2,300 years later.`,

  'Marcus Aurelius': `Marcus Aurelius (121–180 AD) is the closest history has come to Plato's dream of a philosopher-king. He became Roman Emperor in 161 AD and ruled for 19 years — years defined by relentless crisis: plague, war on multiple frontiers, floods, famine. His Meditations were never intended for publication. They were private notes written to himself — a ruler reminding himself how to behave when power, flattery, and exhaustion made virtue difficult. The Meditations draw deeply on Stoic philosophy, particularly the idea that we cannot control what happens to us, only how we respond. He wrote them in Greek, the language of philosophy, not the Latin of Roman power. He died on campaign in 180 AD, the last of the Five Good Emperors.`,

  'Seneca': `Seneca (4 BC–65 AD) was the most successful writer in the Roman world — a playwright, essayist, orator, and advisor to Emperor Nero. He accumulated enormous wealth and political power, which created a tension he was acutely aware of: a Stoic philosopher preaching detachment from wealth while owning multiple villas. His Letters to Lucilius, written in the final years of his life, are among the most intimate documents of the ancient world — an old man writing to a younger friend about time, death, friendship, and how to spend the days we have. In 65 AD, Nero accused him of conspiracy and ordered him to commit suicide. He complied with apparent calm, telling his weeping friends that he left them the one thing no one could take: the example of a life examined.`,

  'Epictetus': `Epictetus (50–135 AD) was born a slave. His master broke his leg deliberately — a demonstration of power. Epictetus reportedly said, during the breaking: "You will break it." Then, when it snapped: "Did I not tell you so?" He was later freed and became one of the most influential teachers in the Roman world. His entire philosophy rests on a single distinction: some things are in our power, and some things are not. Our bodies, reputation, and property are not in our power. Our judgments, desires, and actions are. Everything else is indifferent. His student Arrian wrote down his lectures as the Discourses — one of the most direct and demanding texts in Stoic philosophy. His influence runs from Marcus Aurelius to modern cognitive behavioral therapy.`,

  'Lao Tzu': `Lao Tzu (6th century BC) is a figure of mystery — possibly a real archivist at the Zhou dynasty court, possibly a composite of several thinkers, possibly a legend. The Tao Te Ching, attributed to him, consists of 81 short chapters totaling about 5,000 Chinese characters — one of the shortest and most translated books in history. The text describes the Tao: the Way, the underlying principle of the universe that cannot be named or fully grasped, only aligned with. The Tao Te Ching is not a philosophical argument but a set of observations about how things work — water, emptiness, paradox — and how rulers and individuals might move more effectively by yielding rather than forcing. It has been translated into English more times than any book except the Bible.`,

  'Confucius': `Confucius (551–479 BC) spent most of his life in failure. He was a minor official in the state of Lu who believed deeply that good government required virtuous rulers — and spent decades traveling from state to state trying to find a ruler who would implement his ideas. None did. He returned home at 68, spent his final years teaching, and died convinced his life's work had come to nothing. His students compiled his teachings into the Analects after his death — a collection of conversations, aphorisms, and observations that became the foundational text of Chinese civilization. For two millennia, the Analects shaped Chinese education, government, family structure, and ethics. The examination system that governed Chinese society until 1905 was built around mastery of his teachings.`,

  'Zhuangzi': `Zhuangzi (369–286 BC) was the great poet-philosopher of Taoism, and perhaps the most entertaining philosopher who ever lived. His book — also called the Zhuangzi — is full of talking animals, absurdist parables, and arguments that end in paradox. Where Lao Tzu is spare and oracular, Zhuangzi is playful and wild. He refused political office multiple times. When his wife died, a friend found him singing — he explained that she had returned to the great transformation from which all things emerge, and grief would be a refusal to understand nature. His central insight is that our categories — useful and useless, big and small, life and death — are conventions, not absolute truths. The universe is indifferent to our classifications, and wisdom lies in moving fluidly rather than grasping.`,

  'Rumi': `Jalāl ad-Dīn Muhammad Rumi (1207–1273) was a 13th-century Persian scholar, jurist, Islamic theologian, and mystic who lived in what is now Turkey. The pivotal event of his life was meeting a wandering dervish named Shams of Tabriz in 1244. Their friendship — intense, mysterious, transformative — shattered Rumi's identity as a respectable scholar and unlocked something incandescent. When Shams disappeared (likely murdered by Rumi's jealous disciples), Rumi poured his grief and longing into poetry. The Masnavi, his masterwork, is a six-volume, 25,000-verse epic often called "the Quran in Persian." His Divan-e Shams contains over 40,000 verses. He remains the best-selling poet in the United States, though most translations are loose adaptations that soften his Islamic mysticism. The original is far stranger and more demanding.`,

  'Siddhartha Gautama (The Buddha)': `Siddhartha Gautama (563–483 BC) was born into a royal family in what is now Nepal. According to tradition, his father tried to shield him from suffering — but at 29, encounters with old age, sickness, and death shattered his sheltered life. He left his palace, wife, and infant son to seek the end of suffering. After years of extreme asceticism that nearly killed him, he sat under a Bodhi tree in Bodh Gaya and resolved not to move until he understood the nature of suffering. The insight that came — the Four Noble Truths and the Eightfold Path — became Buddhism. He spent the remaining 45 years of his life teaching, refusing to claim divine status, insisting his understanding was available to anyone willing to examine their own mind with honesty.`,

  'Friedrich Nietzsche': `Friedrich Nietzsche (1844–1900) was the son of a Lutheran pastor who died when Nietzsche was 4. He was a child prodigy who became the youngest-ever professor of classical philology at Basel at age 24. His friendship with Richard Wagner, which he later described as the central mistake of his intellectual life, ended in bitter estrangement. He spent his mature years traveling between cheap boarding houses in Switzerland, Italy, and France, writing some of the most influential and most misunderstood texts in philosophy. He was not a German nationalist — he despised nationalism. He was not an antisemite — he broke with his sister partly over her virulent antisemitism. He was a relentless diagnostician of European culture's hidden contradictions. In January 1889, he collapsed in the street in Turin, embracing a horse that was being whipped, and never recovered his sanity.`,

  'Søren Kierkegaard': `Søren Kierkegaard (1813–1855) lived his entire life in Copenhagen and rarely left. His most formative act was breaking off his engagement to Regine Olsen in 1841 — an event that haunted him for the rest of his life and surfaces in nearly everything he wrote. He was a fierce critic of the established Danish Church, which he felt had made Christianity so comfortable and respectable that it no longer required any of the radical commitment Christ had demanded. He wrote under a bewildering array of pseudonyms to prevent readers from taking his ideas as straightforward doctrine — he wanted them to think, not just believe. He is considered the father of existentialism. He died at 42, having spent his entire inheritance, collapsing on the street after a productive day of writing.`,

  'Albert Camus': `Albert Camus (1913–1960) was born in colonial Algeria to a family so poor his mother could neither read nor write. He grew up in a two-room apartment in Algiers and was only able to attend school because a teacher, Louis Germain, recognized his intelligence and advocated for him (Camus thanked Germain in his Nobel Prize acceptance speech). He contracted tuberculosis at 17, which shaped his relationship with mortality. He worked as a journalist, playwright, editor, and novelist — and was simultaneously part of the French Resistance during the Nazi occupation. His philosophy of the absurd — the confrontation between humanity's need for meaning and the universe's silence — was forged in direct encounter with violence, poverty, and death. He was awarded the Nobel Prize in 1957. He died in a car accident in 1960 at age 46, carrying an unused train ticket in his pocket.`,

  'Jean-Paul Sartre': `Jean-Paul Sartre (1905–1980) was arguably the most famous intellectual in the world during the 1950s and 60s. He wrote plays, novels, screenplays, literary criticism, and dense philosophical treatises — all while chain-smoking and participating in nearly every major political controversy of his era. His fundamental insight — that existence precedes essence, that we have no pre-given human nature and must create our own meaning — was both liberating and terrifying. He was offered the Nobel Prize in Literature in 1964 and refused it, saying that a writer who accepts official honors becomes an institution and loses independence. His relationship with Simone de Beauvoir lasted 51 years and was one of the most intellectually productive partnerships in the history of ideas.`,

  'Simone de Beauvoir': `Simone de Beauvoir (1908–1986) came second in the agrégation — the most prestigious French academic examination — in 1929. The person who came first was Sartre. They were 21 and 24. Their partnership lasted the rest of their lives. Her 1949 book The Second Sex is one of the founding texts of feminist philosophy — a 900-page analysis of how women are defined as "Other" in a world built by and for men. She was refused the Nobel Prize multiple times. She wrote novels, memoirs, philosophy, and political essays. In her memoir A Very Easy Death, she described watching her mother die and the terror of confronting mortality in the body of someone you love. She died in 1986 and was buried beside Sartre in Montparnasse cemetery.`,

  'Carl Jung': `Carl Gustav Jung (1875–1961) grew up in rural Switzerland, the son of a pastor who was losing his faith. From childhood he experienced vivid dreams and what he would later call "two personalities" — a conventional schoolboy and an ancient, wise inner self. He trained as a psychiatrist, worked with Freud for six years, and then broke with him in 1912 in a rupture that was personally devastating and intellectually liberating. The years after the split, which Jung called his "confrontation with the unconscious," produced the foundations of analytical psychology: the collective unconscious, archetypes, the shadow, the anima and animus, individuation. He filled over 200 notebooks during a period of psychological crisis that he suspected was a form of madness. The Red Book, his illustrated record of that period, was hidden for 50 years and published in 2009.`,

  'Viktor Frankl': `Viktor Frankl (1905–1997) was a Viennese psychiatrist who had already developed logotherapy — the therapeutic approach centered on the human search for meaning — before the war. In 1942, he and his entire family were deported to the Nazi concentration camps. His wife, brother, and parents were killed. He survived Auschwitz and three other camps. Man's Search for Meaning, written in nine days after liberation, describes his experiences and argues that even in the most extreme suffering, humans retain the freedom to choose their attitude. It has sold over 16 million copies and has been called one of the most influential books in America. Frankl returned to Vienna after the war, rebuilt his practice, and continued writing and teaching until his death at age 92.`,

  'Erich Fromm': `Erich Fromm (1900–1980) was a German-American psychologist and philosopher whose work sat at the intersection of Freudian psychoanalysis, Marxist social theory, and humanist ethics. He fled Germany in 1933 as the Nazis rose to power. His 1941 book Escape from Freedom argued that modern humans, freed from the constraints of the medieval world, were overwhelmed by the anxiety of that freedom — and sought to escape it through authoritarianism, conformity, or destructiveness. His 1956 book The Art of Loving argued that love is not a feeling that happens to you but a capacity you develop through practice — and that modern culture systematically undermines the conditions for genuine love.`,

  'Carl Rogers': `Carl Rogers (1902–1987) grew up in a strict, religious household in Illinois. His early interest was agriculture — he even attended agricultural college — before switching to theology, then psychology. He developed person-centered therapy in reaction against the prevailing model of the therapist as an authority who diagnoses and treats. Rogers believed that humans have an innate tendency toward growth and that what holds people back is the conditional regard they receive — love and acceptance contingent on being a certain way. His therapy offered unconditional positive regard, empathy, and authenticity. His influence extends far beyond clinical psychology into education, organizational development, and conflict resolution.`,

  'William James': `William James (1842–1910) was the first person to teach a psychology course in the United States and one of the founders of American philosophy. He struggled with severe depression for years in his 20s, at one point deciding to live as if free will were real — not because he could prove it but because the assumption was necessary for a livable life. This pragmatist approach — judge ideas by their practical consequences — became his signature philosophical contribution. His Principles of Psychology (1890) was so comprehensive and beautifully written that it defined the field for a generation. His brother was Henry James, the novelist. They had one of the most complex sibling relationships in literary history.`,

  'Rainer Maria Rilke': `Rainer Maria Rilke (1875–1926) was born in Prague, then part of the Austro-Hungarian Empire. His mother dressed him as a girl until he was six, trying to replace a daughter who had died in infancy. He had a miserable time at military school, which he described as years of organized humiliation. His adult life was a series of artistic retreats — often in castles loaned by aristocratic patrons — punctuated by intense relationships and periods of silence when he could not write. His major works came in two bursts separated by ten years of near-silence: the Duino Elegies and Sonnets to Orpheus were both completed in a three-week period in 1922, after a decade of waiting. He described the experience as dictation. He died from leukemia in 1926, apparently triggered by a rose thorn.`,

  'Virginia Woolf': `Virginia Woolf (1882–1941) grew up in a house full of Victorian intellectuals — her father was the literary critic Leslie Stephen — and was educating herself in the family library while her brothers went to Cambridge. She was sexually abused by her half-brothers as a child and adolescent. She experienced severe mental breakdowns throughout her life, including attempted suicides. She and her husband Leonard founded the Hogarth Press in 1917 and published it from their living room, which gave her complete editorial freedom. Her novels — Mrs Dalloway, To the Lighthouse, The Waves — broke apart the conventions of Victorian fiction and rebuilt them around the interior life, the movement of consciousness, the texture of a single day. In 1941, as the bombs fell on London and she felt another breakdown coming, she filled her coat pockets with stones and walked into the River Ouse.`,

  'James Baldwin': `James Baldwin (1924–1987) grew up in Harlem, the eldest of nine children, stepson of a fiercely religious preacher he both loved and feared. He left America for Paris at 24, carrying the manuscript of his first novel and $40. He spent much of his adult life in Europe — not because he hated America, but because distance gave him the clarity to write about it honestly. His essays in Notes of a Native Son, The Fire Next Time, and Nobody Knows My Name are among the most precise analyses of American racism ever written. He was deeply involved in the Civil Rights Movement. He died of cancer in France in 1987. His literary executor found, in his apartment, 30 unfinished manuscripts.`,

  'Franz Kafka': `Franz Kafka (1883–1924) worked as an insurance lawyer in Prague by day and wrote at night. He published almost nothing during his lifetime — a few stories. He instructed his friend and literary executor Max Brod to burn everything after his death. Brod did not. Instead, he published The Trial, The Castle, and Amerika — the three unfinished novels that made Kafka one of the defining writers of the 20th century. Kafka's fiction is about bureaucracy, power, and the helplessness of the individual before systems that are vast, arbitrary, and indifferent to human meaning. He was acutely aware of his position as a German-speaking Czech Jew — belonging fully to none of the worlds that surrounded him. He died of tuberculosis at 40.`,

  'Albert Einstein': `Albert Einstein (1879–1955) was failed by multiple educational systems before he changed physics forever. He struggled in the rigid German educational system, was rejected by ETH Zurich on his first application, and spent two years unable to find an academic job after graduating — working as a technical expert third class at the Swiss patent office. It was there, evaluating applications from engineers, that he developed the ideas he published in 1905: the special theory of relativity, the photoelectric effect (which won him the Nobel Prize), and Brownian motion. All in one year. He was 26. He spent the rest of his life at the Institute for Advanced Study in Princeton, searching unsuccessfully for a unified field theory, and speaking out against nuclear weapons and for civil rights.`,

  'Richard Feynman': `Richard Feynman (1918–1988) was one of the great explainers in the history of science — someone who could describe quantum mechanics to a lay audience with the same directness he brought to his Nobel Prize-winning work on quantum electrodynamics. He worked on the Manhattan Project at Los Alamos, where he occupied himself by cracking safes and driving the security staff mad. His Feynman Lectures on Physics, delivered at Caltech in the early 1960s, remain the most celebrated introduction to physics ever written. He died of kidney cancer in 1988, famously refusing a transfer to another hospital: "I'd hate to die twice. It's so boring."`,

  'Carl Sagan': `Carl Sagan (1934–1996) grew up in Brooklyn and first visited a library at age 5. The librarian, at his request, got him books about stars. His life's work was the same project: making the universe legible and wondrous to people who had never thought to look up. His 1980 television series Cosmos was watched by 500 million people in 60 countries — still the most widely watched documentary series in television history. His novel Contact became a film with Jodie Foster. He was instrumental in the Voyager Golden Record, the message sent into interstellar space in case another civilization finds it. He died of pneumonia following bone marrow cancer in 1996, having spent his final years warning about climate change, nuclear weapons, and the dangers of pseudoscience.`,

  'Leo Tolstoy': `Leo Tolstoy (1828–1910) was a Russian count who fought in the Crimean War, ran up enormous gambling debts, managed his estate at Yasnaya Polyana, married Sophia Behrs (who hand-copied War and Peace seven times), fathered 13 children, and became one of the two or three greatest novelists in history. Then, in his 50s, he had a spiritual crisis so severe he nearly killed himself. He emerged from it as a radical Christian anarchist: he gave away his copyrights, tried to give away his estate, condemned the Russian Orthodox Church, and was excommunicated. In 1910, at age 82, he finally left home — abandoning his wife after years of conflict — and died of pneumonia in a railway stationmaster's house 10 days later.`,

  'Fyodor Dostoevsky': `Fyodor Dostoevsky (1821–1881) was arrested at 27 for membership in a liberal reading circle. He was condemned to death, subjected to a mock execution — taken before a firing squad, blindfolded — before the order was commuted at the last moment. He spent four years in a Siberian labor camp followed by six years of military service. This experience of near-death and suffering became the foundation of everything he wrote afterward. His great novels — Crime and Punishment, The Idiot, The Brothers Karamazov — are relentless investigations into guilt, redemption, God, and the psychology of extremity. He was epileptic, chronically in debt, and compulsively gambled away his and his wife's money. The Brothers Karamazov was completed in 1880; he died two months after its publication.`,

  'Friedrich Nietzsche': `Friedrich Nietzsche (1844–1900) was the son of a Lutheran pastor who died when Nietzsche was 4. He was a child prodigy who became the youngest-ever professor of classical philology at Basel at age 24. His mature philosophy was built on a single question: what happens to morality, meaning, and culture when the foundational belief in God — which had organized European civilization for 1,500 years — is no longer credible? His answer was not despair but a challenge: to create new values, to affirm life completely, to become what you are. In January 1889, he collapsed in the street in Turin and never recovered his sanity. The last decade of his life was spent in mental incapacity, cared for by his sister — who later distorted his legacy by associating his ideas with German nationalism.`,

  'Ludwig Wittgenstein': `Ludwig Wittgenstein (1889–1951) was born into one of the wealthiest families in Vienna and gave away his entire inheritance. He studied engineering, became interested in the philosophy of mathematics, went to Cambridge to study with Bertrand Russell, and wrote the Tractatus Logico-Philosophicus in the trenches of World War I while fighting for the Austrian army. The Tractatus is one of the strangest and most important works in philosophy — an attempt to show the logical structure of language and reality, ending with the proposition: "Whereof one cannot speak, thereof one must be silent." He then concluded that he had solved philosophy and became a primary school teacher in rural Austria. He returned to philosophy 10 years later, convinced he had been wrong. His Philosophical Investigations, finished shortly before his death, is a complete dismantling of his earlier views.`,

  'Michel Foucault': `Michel Foucault (1926–1984) grew up in Poitiers, France, the son of a surgeon who wanted him to follow the same path. He studied psychology, worked briefly in psychiatric hospitals, and developed a deep suspicion of how institutions use the language of medicine and science to exercise power over people who deviate from norms. His major works — Madness and Civilization, The Birth of the Clinic, Discipline and Punish, The History of Sexuality — are historical analyses of how concepts like madness, illness, criminality, and sexuality have been constructed to serve social control. He died of AIDS-related illness in 1984, one of the first prominent intellectuals to do so.`,

  'Simone Weil': `Simone Weil (1909–1943) was one of the most radical and demanding thinkers of the 20th century. She was brilliant, physically frail, and constitutionally unable to separate her philosophy from her life. She worked in a Renault car factory to understand the experience of industrial labor, fought briefly in the Spanish Civil War, worked as a farmhand. During the German occupation of France, she refused to eat more than the ration allocated to people in occupied France, weakening her constitution. She died in a sanatorium in Kent, England, at 34, of tuberculosis exacerbated by malnutrition. Her notebooks and letters, most published posthumously, combine mystical theology, political philosophy, and a moral intensity that few thinkers have matched.`,

  'Pablo Picasso': `Pablo Picasso (1881–1973) was the most famous artist of the 20th century and one of its most morally complicated. Born in Málaga, Spain, he showed extraordinary facility from childhood — his father, an art teacher, reportedly gave Picasso his own brushes when he realized his son had surpassed him at age 13. He moved to Paris, developed Cubism with Georges Braque, and spent the next seven decades relentlessly reinventing himself. He was also, by many accounts, a brutal presence in the lives of the women he loved — several had breakdowns or died by suicide after their relationships with him ended. Guernica, painted in response to the Nazi bombing of a Basque town in 1937, is considered the most important political work of 20th-century art.`,

  'Frida Kahlo': `Frida Kahlo (1907–1954) contracted polio at age 6. At 18, she was in a bus accident that shattered her spine, collarbone, ribs, pelvis, and right leg, and drove a steel handrail through her body. She underwent over 35 surgeries. She began painting during her recovery, lying on her back in a specially made bed with a mirror overhead, making her own face and body the primary subject of her work. She married Diego Rivera twice. Her paintings are simultaneously surrealist and documentary — she insisted they were not dreams but her reality. She died at 47; her last diary entry reads: "I joyfully await the exit — and I hope never to return."`,

  "Georgia O'Keeffe": `Georgia O'Keeffe (1887–1986) grew up on a farm in Wisconsin and decided at 10 she wanted to be an artist. She studied in Chicago and New York, then spent several years teaching school in Texas — where the vast, flat landscape began shaping her aesthetic. In 1916, Alfred Stieglitz exhibited her drawings in New York without her permission; they had a long and difficult relationship thereafter, eventually marrying. She spent decades in New York society before moving permanently to New Mexico in 1949, three years after Stieglitz's death. The Taos desert, the bleached skulls, the flower close-ups: her mature work came from total commitment to seeing things directly, without convention, on her own terms. She died in 1986 at 98, having spent her final years mostly blind.`,

  'Vincent van Gogh': `Vincent van Gogh (1853–1890) sold exactly one painting in his lifetime. He spent most of his adult life struggling with mental illness, poverty, and a desperate need for human connection. Before painting, he worked as an art dealer, a teacher, a bookshop assistant, and a missionary to Belgian coal miners — a posting he was dismissed from for giving away all his possessions. He only began painting seriously at 27. The 10 years that followed produced over 2,000 works, including the most recognizable paintings in Western art. He moved to Arles in the south of France seeking light, was joined briefly by Gauguin, cut off his ear during a breakdown, and spent the last year of his life voluntarily in a psychiatric hospital. He shot himself at 37 and died two days later, holding his brother's hand.`,

  'Leonardo da Vinci': `Leonardo da Vinci (1452–1519) was the illegitimate son of a notary and a peasant woman, raised by his father in Vinci. His illegitimacy barred him from many professions but freed him from the guild system that constrained other craftsmen. He apprenticed with the Florentine painter Verrocchio, then spent his life moving between the courts of Milan, Venice, Florence, and Rome, working simultaneously as a painter, sculptor, architect, military engineer, anatomist, geologist, botanist, and inventor. He dissected over 30 human bodies. His notebooks, written in mirror script, contain designs for tanks, helicopters, solar power, and plate tectonics — centuries before any of these became reality. He completed relatively few works; he was more interested in problems than solutions. He died in France in 1519, possibly in the arms of Francis I.`,

  'Oscar Wilde': `Oscar Wilde (1854–1900) was born in Dublin, the son of a prominent surgeon father and a poet mother who hosted the city's leading intellectual salon. He won a scholarship to Oxford, where he cultivated an extreme aestheticism — beautiful things for their own sake, against Victorian utilitarianism. He moved to London, married, had two sons, and became the most brilliant conversationalist and wit in England. His plays — The Importance of Being Earnest, An Ideal Husband — were running simultaneously in the West End when his world collapsed. He sued the Marquess of Queensberry for libel, lost, was prosecuted for gross indecency with men, found guilty, and sentenced to two years' hard labor. The imprisonment broke his health. He died in Paris three years later, impoverished, at 46.`,

  'Mark Twain': `Mark Twain (1835–1910) was born Samuel Langhorne Clemens in Missouri. He worked as a printer's apprentice, riverboat pilot (his pen name comes from a depth-sounding call), silver miner, and journalist before finding his voice as a writer. Huckleberry Finn (1884) is considered the first great American novel — a portrait of American freedom and American racism filtered through the consciousness of a boy on a raft. In the last decades of his life, following the deaths of his wife and two daughters and financial ruin from failed investments, Twain became increasingly dark and bitter. The Autobiography, which he stipulated should not be published until 100 years after his death, is a sustained howl of grief and rage. He died in 1910, the same year Halley's Comet appeared — as he had predicted, having been born during its previous appearance.`,

  'William Shakespeare': `William Shakespeare (1564–1616) was born in Stratford-upon-Avon to a glove-maker who was prominent in local politics before financial troubles reduced his circumstances. Shakespeare attended the local grammar school, left for London around 1585, and by 1592 was established enough as an actor and playwright to be attacked in print by a rival. He was a shareholder in the Globe Theatre and the King's Men, the most successful acting company in Elizabethan England. He wrote 37 plays and 154 sonnets in a roughly 25-year career. We know almost nothing about his inner life — no letters, no diary. Everything personal we know about him comes from legal documents about business disputes. He retired to Stratford around 1613 and died three years later. His collected plays were published in the First Folio in 1623, seven years after his death.`,

  'Mahatma Gandhi': `Mohandas Karamchand Gandhi (1869–1948) trained as a lawyer in England and practiced in South Africa, where his experience of racial discrimination radicalized him. He developed satyagraha — truth-force or soul-force — as a method of nonviolent resistance, first in South Africa then in India. He led campaigns of civil disobedience that eventually ended British rule over India, including the Salt March of 1930, where he walked 240 miles to the sea to make salt illegally. He lived simply, spinning his own cloth, fasting as a political instrument, believing that the method of struggle must embody the society you wish to create. He was assassinated by a Hindu nationalist on January 30, 1948, five months after Indian independence.`,

  'Langston Hughes': `Langston Hughes (1902–1967) was one of the central figures of the Harlem Renaissance — the flowering of African American literature, art, and music in New York in the 1920s. He grew up largely raised by his grandmother after his parents separated, then lived in several cities before landing in Harlem. His first major poem, "The Negro Speaks of Rivers," was written on a train to Mexico at age 17. He worked as a busboy, seaman, and doorman while writing, and was discovered when poet Vachel Lindsay found his poems left beside a plate at the restaurant where Hughes worked. His work drew on jazz, blues, and vernacular Black speech — he was insisting that the lives and speech of ordinary Black Americans were as worthy of art as anything in the Western canon.`,

  'E.E. Cummings': `E.E. Cummings (1894–1962) was arrested by French military authorities in 1917 for "suspicious correspondence" — his letters home were too candid about the chaos of wartime France. He spent three months in a detention camp, an experience he described in his first book, The Enormous Room. His poetry is immediately recognizable: lowercase typography, unconventional punctuation, words broken mid-line, grammar inverted. These weren't affectations — they were attempts to free language from the mechanical conventions that dulled its power. He was also a trained visual artist who painted every morning. He described his artistic aims in a single deceptively simple statement: "it takes courage to grow up and become who you really are."`,

  'Pablo Neruda': `Pablo Neruda (1904–1973) was born in a small town in southern Chile and published his first poem at 13. Twenty Poems of Love and a Song of Despair, published when he was 19, became one of the best-selling poetry books in the Spanish language. He worked as a Chilean consul in Burma, Ceylon, Java, and Spain; his experiences in Spain during the Civil War — watching friends die and fascism destroy a republic — transformed him politically and poetically. He joined the Communist Party and was forced into exile in 1948. He eventually returned to Chile and was the ambassador to France under Salvador Allende. He died of heart failure on September 23, 1973, 12 days after the military coup that killed Allende. The military ransacked his house as he lay dying.`,

  'Sylvia Plath': `Sylvia Plath (1932–1963) was the only child of Otto Plath, a German immigrant who taught at Boston University and who died of untreated diabetes when Sylvia was 8. Her father's death — and her rage at his abandonment — runs through everything she wrote. She won every prize, scholarship, and fellowship her institutions offered, suffered a severe breakdown at 20 and attempted suicide, and wrote about it in The Bell Jar. She married the poet Ted Hughes in 1956, had two children, separated from him after his affair, and was living alone with the children in London during the coldest winter in a century when she died by suicide in February 1963. She was 30. Ariel, the collection she had assembled before her death, was published posthumously and is one of the most powerful and devastating collections in the English language.`,

  'Walt Whitman': `Walt Whitman (1819–1892) worked as a journalist, printer, government clerk, and wound-dresser in Civil War hospitals — an experience that marked him permanently. Leaves of Grass, which he self-published in 1855 and kept revising for the rest of his life, is one of the great acts of literary self-creation: Whitman invented a new kind of American poetry — vast, inclusive, democratic, sensual, cataloguing the entire continent and every person in it. He wrote in free verse at a time when no serious poet wrote in free verse. He mailed a copy to Emerson, who wrote back: "I greet you at the beginning of a great career." Whitman had the letter printed on the cover of the next edition without asking permission. He spent his old age in a modest house in Camden, New Jersey, receiving a steady stream of pilgrims from around the world.`,

  'Emily Dickinson': `Emily Dickinson (1830–1886) spent most of her adult life in a single house in Amherst, Massachusetts. She rarely left. She dressed in white. She lowered gingerbread to children from her window in a basket. She wrote over 1,800 poems and published fewer than a dozen in her lifetime — always anonymously, always against her wishes when it happened. Her poems arrived at her editors in small, hand-sewn booklets called fascicles. After her death, her sister found 40 such booklets in a locked box. The poems use unconventional dashes, slant rhymes, and compressed syntax that felt alien to 19th-century readers and took a century to be fully appreciated. She wrote about death, immortality, nature, and consciousness with a directness that still shocks.`,

  'Alan Watts': `Alan Watts (1915–1973) was a British philosopher who moved to America and spent his life translating Eastern philosophy — particularly Zen Buddhism and Taoism — into language that Western audiences could absorb. He was an Episcopal priest for a time, then left the ministry to write and lecture. He wrote over 25 books and was a central figure in the counterculture of the 1950s and 60s. His lectures, recorded informally, circulate widely on the internet and YouTube, where his distinctive voice and gift for analogy reach audiences he could never have imagined. He died in his sleep at 58, aboard his houseboat in Sausalito. His core message — pay attention, stop grasping, the present moment is enough — was a direct challenge to the acceleration anxiety of American life.`,

  'Martin Luther King Jr.': `Martin Luther King Jr. (1929–1968) was the son and grandson of Baptist ministers in Atlanta. He was ordained at 15. He earned a PhD in systematic theology from Boston University, where he encountered the philosophy of personalism and deepened his engagement with Gandhi's methods. He became pastor of Dexter Avenue Baptist Church in Montgomery, Alabama, at 25 — arriving just in time for the Montgomery Bus Boycott, which launched the modern Civil Rights Movement. He led campaigns in Birmingham, Selma, Chicago, and Washington, was jailed 29 times, won the Nobel Peace Prize in 1964, and was surveilled by the FBI for years. He was assassinated on April 4, 1968, in Memphis, where he had gone to support striking sanitation workers. He was 39.`,

  'Nelson Mandela': `Nelson Mandela (1918–2013) trained as a lawyer, became a leader of the African National Congress Youth League, and co-founded Umkhonto we Sizwe — the armed wing of the ANC — after the Sharpeville massacre convinced him that nonviolent resistance alone could not defeat apartheid. He was convicted of sabotage in 1964 and sentenced to life imprisonment on Robben Island. He was imprisoned for 27 years. He could have been released earlier if he had renounced violence and accepted a homeland; he refused. He was released in 1990 and spent the next four years negotiating the end of apartheid with the National Party government. He became South Africa's first democratically elected president in 1994. He died at 95, one of the last figures of unambiguous moral authority in global politics.`,

  'Tadao Ando': `Tadao Ando (born 1941) never studied architecture formally. He was largely self-taught, learning by traveling — alone, on a cargo ship from Osaka to Europe and back — and by reading. Before becoming an architect, he boxed professionally. His architecture is built on paradox: he uses the most elemental materials (concrete, water, light) to create spaces of extraordinary spiritual intensity. His first major building, the Row House in Sumiyoshi (1976), was a concrete box inserted into a poor neighborhood in Osaka — it replaced the middle third of a traditional townhouse with an open courtyard exposed to the sky. The family had to walk outside to get from the bedroom to the kitchen. Ando saw this as a challenge to reclaim the experience of nature within urban life. He won the Pritzker Prize in 1995.`,

  'Louis Kahn': `Louis Kahn (1901–1974) was born in poverty on the Estonian island of Saaremaa and came to America as a child. He was disfigured by fire at age 3. He worked for years in Philadelphia before his career truly began at 50 — an unusually late start in architecture. His buildings feel ancient: the Salk Institute in La Jolla, the National Assembly in Dhaka, the Kimbell Art Museum in Fort Worth are among the most powerful spaces built in the 20th century. He was obsessed with light — natural light as the primary material of architecture. He died of a heart attack in a public bathroom at Penn Station in New York, returning from a project in Bangladesh. His briefcase contained no identification; he was listed as an unknown person for three days before he was identified.`,

  'Frank Lloyd Wright': `Frank Lloyd Wright (1867–1959) was one of the most productive and scandalous architects in American history. He designed over 1,000 buildings in a career that spanned 70 years. He ran away from his employer Louis Sullivan, started an affair with a client's wife (she was later murdered by a servant who set fire to his studio), went bankrupt multiple times, and was nearly destroyed by scandal. He kept building. Fallingwater (1935), designed at 68 after a period of professional irrelevance, is considered the greatest house ever built. He designed the Guggenheim Museum in New York, completed the year he died at 91. His private life was marked by serial infidelity, financial recklessness, and enormous personal magnetism.`,

  'Mies van der Rohe': `Ludwig Mies van der Rohe (1886–1969) was the son of a stonemason who never went to architecture school. He worked as an apprentice, absorbed the lessons of early 20th-century modernism through Peter Behrens's office (where he worked alongside Gropius and Le Corbusier), and became one of the three most influential architects of the century. His Barcelona Pavilion (1929) is a meditation on space, proportion, and the relationship between inside and outside. He directed the Bauhaus from 1930 until the Nazis forced it to close in 1933, then emigrated to America, where he rebuilt the IIT campus in Chicago. His phrase "less is more" is the most quoted sentence in design history.`,

  'Akira Kurosawa': `Akira Kurosawa (1910–1998) wanted to be a painter before he became a filmmaker. He directed 30 films over 57 years, including Seven Samurai, Rashomon, Ikiru, and Ran — works that redefined what cinema could do. Rashomon (1950) introduced Western audiences to Japanese cinema and to the idea that all narratives are constructed from a point of view. He suffered a severe breakdown in 1971, attempting suicide after a film was removed from his control. He returned to filmmaking and made what many consider his greatest works in his 70s and 80s. His influence extends to every major filmmaker since: George Lucas, Francis Ford Coppola, Steven Spielberg, and countless others cite him as foundational.`,

  'Miles Davis': `Miles Davis (1926–1991) was the most restless innovator in the history of jazz. He was the son of a prosperous dentist from East St. Louis and enrolled at the Juilliard School at 17, ostensibly to study classical music. He was really there to find Charlie Parker and Dizzy Gillespie. Over the next 45 years, he reinvented jazz roughly every decade: cool jazz (Birth of the Cool, 1949), hard bop, modal jazz (Kind of Blue, 1959, the best-selling jazz album of all time), jazz-rock fusion (Bitches Brew, 1970). He suffered severe personal problems — addiction, violent relationships, years of withdrawal — and returned each time with something unrecognizable. His autobiography describes racism in America with the same unflinching directness he brought to music.`,

  'Grace Hopper': `Grace Hopper (1906–1992) was a mathematician who became a rear admiral in the US Navy and one of the pioneers of computer programming. She joined the Navy Reserve after Pearl Harbor, was assigned to the Bureau of Ships Computation Project at Harvard, and worked on the Mark I computer. She developed the first compiler — a program that translates human-readable instructions into machine code — making programming accessible to people who couldn't write in binary. The story that she literally found a "bug" in a computer — a moth caught in a relay of the Mark II — gave the term its modern usage. She was 85 when she retired from active naval duty, the oldest active-duty commissioned officer in the United States.`,

  'Marshall McLuhan': `Marshall McLuhan (1911–1980) was a Canadian literary critic who became the first theorist of electronic media. He converted to Catholicism in 1937, taught at universities in Canada and the United States, and published Understanding Media in 1964, which became an unlikely bestseller. His central insight — that the form of a medium shapes its users as much as its content — was disorienting to people accustomed to thinking about content in isolation. "The medium is the message" meant that television changed society not primarily through what it showed but through the way watching television shaped perception, attention, and social relationships. He predicted the internet decades before it existed.`,

  'E.E. Cummings': `E.E. Cummings (1894–1962) grew up in Cambridge, Massachusetts, the son of a Unitarian minister and Harvard professor. He graduated from Harvard, then in 1917 went to France as an ambulance driver — and was arrested by French authorities who suspected his unconventional letters home indicated disloyalty. Three months in a detention camp produced his first book. His poetry is immediately recognizable: lowercase letters, fractured syntax, words broken and rearranged to release the energy trapped in conventional usage. He was deeply influenced by Cubism — the same impulse to see a thing from multiple angles simultaneously. He painted every day for decades and considered his visual work as important as his poetry.`,

  'Andrei Tarkovsky': `Andrei Tarkovsky (1932–1986) made only seven feature films and is considered one of the greatest directors in cinema history. His father was the poet Arseny Tarkovsky; his parents separated when he was 3. He studied at the Soviet film school VGIK and made Ivan's Childhood (1962) at 30, winning the Golden Lion at Venice. His subsequent films — Andrei Rublev, Solaris, Mirror, Stalker, The Sacrifice — are among the slowest, most demanding, and most transcendent works in cinema. He defected from the Soviet Union in 1984 and died of lung cancer in Paris in 1986, during the making of The Sacrifice. He was 54. His book Sculpting in Time remains the most important statement by any filmmaker about what cinema is for.`,

  'Stanley Kubrick': `Stanley Kubrick (1928–1999) was a high school dropout from the Bronx who became a chess hustler in Washington Square Park, then a photographer for Look magazine, then one of the most controlled and demanding filmmakers in cinema history. He moved to England in 1961 and almost never left, making films at an average rate of one every five years. His 13 features — Spartacus, Lolita, Dr. Strangelove, 2001, A Clockwork Orange, The Shining, Full Metal Jacket, Eyes Wide Shut — span genres but share an obsession: the gap between human pretension and human behavior. He was legendary for his perfectionism — shooting scenes hundreds of times, controlling every aspect of production, maintaining a near-total grip on how his films were shown.`,

  'Pablo Neruda': `Pablo Neruda (1904–1973) wrote "Twenty Love Poems and a Song of Despair" at 19 and it became one of the best-selling poetry collections in the Spanish language. He served as Chilean consul in multiple countries and was radicalized by witnessing the Spanish Civil War. He won the Nobel Prize in Literature in 1971. He died 12 days after the military coup that killed Salvador Allende, his friend and president — of heart failure in Santiago, his house ransacked by soldiers.`,

  'Jean-Michel Basquiat': `Jean-Michel Basquiat (1960–1988) was the son of a Haitian father and Puerto Rican mother, raised in Brooklyn. He ran away from home at 15, sold handmade postcards and sweatshirts in lower Manhattan, and spray-painted cryptic texts around SoHo under the tag SAMO. He was discovered by art world figures at 19, became friends with Andy Warhol, and in five years produced a body of work — combining text, symbols, figures, and paint — that made him one of the most important painters of his generation. He died of a heroin overdose at 27. The texts in his paintings — anatomy diagrams, historical facts, brand names, crossed-out words — are meditations on the Black body in a world built to erase it.`,

  'Andy Warhol': `Andy Warhol (1928–1987) grew up in Pittsburgh, the son of Slovak Catholic immigrants, and was a sickly child who spent months in bed reading movie magazines and comic books — developing his lifelong obsession with celebrity and mass culture. He moved to New York, became a highly successful commercial illustrator, then in the early 1960s began making art from the images of consumer culture: Campbell's soup cans, Brillo boxes, celebrity portraits. The Factory, his studio, was the center of New York's avant-garde scene throughout the 60s. He was shot and severely wounded by Valerie Solanas in 1968. He never fully recovered his health. He died of cardiac arrhythmia following routine surgery in 1987.`,

  'Roland Barthes': `Roland Barthes (1915–1980) was one of the central figures of French structuralism and post-structuralism. He lost his father in World War I when he was less than a year old. He grew up with his mother, to whom he was deeply attached. His essays — Mythologies, S/Z, A Lover's Discourse, Camera Lucida — examined how meaning is constructed in language, images, advertising, sport, fashion, and literature. Camera Lucida, written after his mother's death, is a meditation on photography, grief, and what it means to love someone who is gone. He was struck by a laundry van while crossing the street in Paris in 1980 and died a month later from injuries.`,

  'Alan Watts': `Alan Watts (1915–1973) was an English philosopher who spent his life translating Eastern thought — particularly Zen and Taoism — for Western audiences. He was ordained as an Anglican priest and left the ministry. He moved to California, lectured at the American Academy of Asian Studies, and recorded hundreds of talks that still circulate widely on the internet. His gift was not scholarly precision but analogical clarity — the ability to make difficult ideas feel obvious through the right metaphor. His central insistence was that humans suffer primarily from the illusion of being separate from the universe, and that this illusion is dissolved not by belief but by direct experience.`,

  'Dalai Lama XIV': `Tenzin Gyatso, the 14th Dalai Lama (born 1935), was identified as the reincarnation of his predecessor at age 2 in a remote village in northeastern Tibet. He was enthroned as spiritual and political leader of Tibet at age 15, during the Chinese invasion. In 1959, following a failed uprising, he fled to India, where he has lived in exile in Dharamsala ever since, leading the Tibetan government-in-exile and advocating for Tibetan autonomy through dialogue rather than violence. He won the Nobel Peace Prize in 1989. He has engaged extensively with Western scientists, particularly neuroscientists studying meditation, believing that the traditions of Buddhist contemplative practice and Western empirical science have much to learn from each other.`,

  'Thich Nhat Hanh': `Thich Nhat Hanh (1926–2022) was ordained as a Buddhist monk in Vietnam at age 16. During the Vietnam War, he organized relief efforts, founded a school for social work, and traveled to the United States to speak against the war — meeting Martin Luther King Jr., who nominated him for the Nobel Peace Prize in 1967. He was exiled from Vietnam by both sides and lived in France for most of his life, founding Plum Village monastery. His 100+ books, including The Miracle of Mindfulness and Being Peace, brought mindfulness practice to millions of Western readers. He returned to Vietnam in 2018 after 39 years of exile and died there in 2022 at 95.`,
};

// ─── QUOTE-SPECIFIC MEANINGS ─────────────────────────────────────────────────

const QUOTE_MEANINGS: Record<string, { meaning: string; why: string }> = {
  // Socrates
  'The unexamined life is not worth living.': {
    meaning: 'Socrates said this at his trial, defending his life's work of questioning against the death sentence Athens was about to impose. He is not saying that people who don't philosophize deserve to die — he is saying that a life lived without examining one's own beliefs, values, and assumptions is a kind of non-life. To live unexamined is to be driven by inherited ideas, social pressure, and unquestioned impulse rather than conscious choice. The examined life is not necessarily a comfortable one — Socrates died for it — but it is the only one that is genuinely one's own.',
    why: 'In an age of constant distraction and pre-packaged opinion, the examined life requires active resistance. Most of us inherit our beliefs about money, relationships, success, and purpose from our families and culture without ever questioning them. Socrates's challenge is to find the time and courage to ask: do I actually believe this, or was I handed it?',
  },
  'I know that I know nothing.': {
    meaning: 'This is usually misread as false modesty. What Socrates meant was more precise: he had discovered, through conversation with people who claimed expertise, that their knowledge was thin — they could not explain the foundations of what they claimed to know. His advantage was that he at least knew this about himself. Intellectual humility is not ignorance — it is the recognition that certainty is harder to earn than we think, and that the first step toward knowledge is acknowledging the limits of what you currently have.',
    why: 'The Dunning-Kruger effect — the tendency for people with limited knowledge in a domain to overestimate their competence — is one of the most replicated findings in psychology. Socrates was describing this 2,400 years ago. In a media environment that rewards confidence over accuracy, knowing that you don't know is a form of resistance.',
  },
  // Marcus Aurelius
  'You have power over your mind — not outside events. Realize this, and you will find strength.': {
    meaning: 'This comes from the Meditations, the private journal of a Roman Emperor. Marcus Aurelius is reminding himself — not lecturing others — that the fundamental Stoic distinction holds even when you're dealing with plagues, wars, and the deaths of children. What happens to you is largely outside your control. What you do with what happens — how you interpret it, what meaning you assign it, what action you take — is yours. This is not passive acceptance; it is the recognition that fighting reality exhausts energy better spent responding to it.',
    why: 'Modern psychology has largely confirmed the Stoic insight through research on locus of control, cognitive reappraisal, and response flexibility. The space between stimulus and response is where character lives. Expanding that space — by recognizing that the event and your interpretation of it are separate — is one of the most practical skills in human life.',
  },
  'The impediment to action advances action. What stands in the way becomes the way.': {
    meaning: 'Marcus Aurelius is articulating one of the more counterintuitive Stoic practices: the obstacle is not separate from the task, it is the task. When circumstances block your original plan, those circumstances become the new subject of your attention and action. The illness becomes the occasion to practice patience. The betrayal becomes the occasion to practice forgiveness. The failed project becomes the occasion to understand your own assumptions. Nothing is purely wasted if you use the resistance to develop something.',
    why: 'Ryan Holiday built a book around this single passage. Its appeal is not just philosophical — it is a practical method for dealing with the inevitable friction of trying to accomplish anything. The most effective people are those who can pivot from their original intention and treat the pivot itself as the work.',
  },
  'Waste no more time arguing about what a good man should be. Be one.': {
    meaning: 'A characteristically direct rebuke from Marcus Aurelius to himself. He is surrounded by court philosophers, religious debates, and political arguments about virtue — and he cuts through all of it. The gap between discussing ethics and living ethically was as wide in Rome as it is now. The argument is never finished; the moment you stop arguing and start acting is the only closure available.',
    why: 'This applies to every arena where people substitute talking about what should be done for doing it. The meeting that defines values, the mission statement on the wall, the social media post about injustice — all of them can become substitutes for the harder, quieter work of actually being the thing you are describing.',
  },
  // Nietzsche
  'Without music, life would be a mistake.': {
    meaning: 'Nietzsche wrote this in Twilight of the Idols, a work written in the final productive year of his sanity. He is not making a case for music as entertainment or recreation — he is arguing that life requires something that transcends reason, that the purely rational framework of Western civilization is insufficient. Music was for Nietzsche (and for the Greeks) the art that most directly expressed the Dionysian force — chaos, passion, the dark energy of existence that Apollonian rationality tries to organize and suppress. Life without that energy is not fully lived.',
    why: 'There is clinical evidence that music engages the brain more comprehensively than almost any other activity — memory, emotion, movement, language, social connection all activate simultaneously. But Nietzsche's point is deeper than neuroscience: a life organized entirely around utility, productivity, and reason lacks the dimension that makes it feel worth living.',
  },
  'That which does not kill us makes us stronger.': {
    meaning: 'From Twilight of the Idols, this is one of the most quoted lines in Western literature — and one of the most misread. Nietzsche was not making a motivational poster. He was making a precise psychological observation: that certain kinds of hardship, survived and processed, do produce a form of strength — a knowledge of oneself, a calibration of what one can endure, that could not be acquired any other way. The key word is "makes" — not "might make" or "can make." He is describing a process, not a guarantee. Suffering that is not survived or processed does not make you stronger; it breaks you.',
    why: 'Post-traumatic growth — documented in psychology since the 1990s — supports the basic insight: many people who survive serious difficulty report increased strength, deeper relationships, and a richer sense of life\'s meaning. But this is not automatic. It requires reflection, support, and meaning-making. Nietzsche\'s line describes a process, not a consolation.',
  },
  'One must still have chaos in oneself to be able to give birth to a dancing star.': {
    meaning: 'From Thus Spoke Zarathustra, Nietzsche\'s philosophical novel. This is spoken as a warning against the "last men" — people who have optimized for comfort and safety to the point where they are no longer capable of greatness or creation. The chaos Nietzsche refers to is not randomness or disorder but the unresolved, uncomfortable, dangerous energies within the self that have not been organized into conformity. The dancing star — unexpected, self-illuminating — is what becomes possible when those energies are not suppressed.',
    why: 'Creative people in any field recognize the truth here: the work that is most original tends to come from the places of greatest uncertainty and unresolved tension, not from the places of stability and resolution. The impulse to eliminate discomfort often eliminates the generative material along with it.',
  },
  // Seneca
  'Nusquam est qui ubique est — He who is everywhere is nowhere.': {
    meaning: 'Seneca wrote this to Lucilius in the first of his Letters — a warning against the scattered life. To be everywhere is to have spread yourself so thin across so many places, relationships, projects, and distractions that you have no real presence anywhere. The person who is always available, always connected, always moving, is paradoxically absent — never fully in any single place long enough to actually be there. Depth requires staying.',
    why: 'Seneca wrote this in the first century AD. It describes the condition of the smartphone user with uncanny precision. The problem is not modern — it is structural. A life organized around constant movement and availability distributes its energy so widely that nothing receives enough to become real. The antidote is not isolation but intentional depth.',
  },
  'The whole future lies in uncertainty: live immediately.': {
    meaning: 'This is from On the Shortness of Life, one of Seneca\'s most urgent essays. He is not saying to ignore the future or act recklessly. He is pointing out that the future — which we invest enormous energy anticipating, planning for, and worrying about — does not belong to us. It might never arrive. The only time we actually have is now. To constantly defer living until the conditions are right is a form of postponement that can last a lifetime.',
    why: 'The psychological research on this is consistent: people near death overwhelmingly report regret about things not done, not about things done and failed. Seneca\'s advice — live immediately, do the thing now — is a corrective to the procrastination instinct that can consume entire decades in preparation for a future that arrives as something unexpected anyway.',
  },
  // Camus
  'In the midst of winter, I found there was, within me, an invincible summer.': {
    meaning: 'This comes from a short essay called Return to Tipasa, written after Camus returned to Algeria as an adult and found the ruins he had loved as a boy. He had spent years in Paris, in the resistance, in exile of various kinds — physical and metaphysical. The "winter" is not just the season but the historical moment: post-war Europe, the Cold War, the awareness of human capacity for atrocity. The "invincible summer" is not optimism — it is the part of consciousness that persists, that maintains its connection to beauty and aliveness, even when external circumstances are brutal.',
    why: 'Resilience research distinguishes between resilience as the absence of trauma and resilience as the capacity to maintain a core sense of self and meaning while experiencing it. Camus is describing the second kind. The invincible summer is not inherited — it is discovered in the act of returning to what you love.',
  },
  'One must imagine Sisyphus happy.': {
    meaning: 'This is the conclusion of The Myth of Sisyphus, Camus\'s philosophical essay about the absurd. Sisyphus is condemned by the gods to push a boulder up a hill, watch it roll down, and push it up again, forever. Camus reads this as the human condition: we are all doing repetitive, ultimately meaningless tasks in a universe that offers no final justification. His revolutionary claim is that we should imagine Sisyphus happy. Not because the suffering is unreal, but because the act of confronting the absurdity — acknowledging it fully, without denial or false hope — is itself a form of freedom and dignity. The struggle is enough.',
    why: 'Camus was writing against two escape routes he considered dishonest: suicide (saying the absurd is too much) and faith (saying there is a hidden meaning after all). The third option — living fully in the confrontation — is harder and more honest than either. This is the foundation of much secular existential psychology.',
  },
  // Kierkegaard
  'Life can only be understood backwards; but it must be lived forwards.': {
    meaning: 'From Kierkegaard\'s journals. The structure of human experience is fundamentally paradoxical: we can only make sense of what has happened to us in retrospect, after we have enough distance to see the pattern. But we have to make decisions in real time, without that retrospective clarity. This is not a complaint — it is a description of the condition. We cannot wait for understanding before acting; we must act in uncertainty and understand afterward.',
    why: 'This insight has been refined by narrative psychology: humans are meaning-making creatures who construct coherent stories from the past. But the implication is that you cannot know while you are living a chapter whether it is leading somewhere meaningful — you can only know this from the vantage point of a later chapter. This should produce humility about present judgments and patience with present confusion.',
  },
  'The most common form of despair is not being who you are.': {
    meaning: 'From The Sickness Unto Death, Kierkegaard\'s analysis of the forms of despair. He argues that the deepest despair is not the dramatic kind — grief, loss, crisis — but the quiet despair of living as someone other than yourself. People build lives based on what others expect, what society rewards, what seems safe or respectable, and gradually lose contact with whatever was genuinely their own. This is a slow, usually invisible catastrophe.',
    why: 'This anticipates a century of existential psychology. Authenticity — living from your own values rather than adopted ones — has been consistently associated with life satisfaction, resilience, and genuine relationship. The problem Kierkegaard identifies is structural: the pressure to conform is constant and the authentic self is fragile and hard to hear in the noise.',
  },
  // Rilke
  'Be patient toward all that is unsolved in your heart and try to love the questions themselves.': {
    meaning: 'This is from Letters to a Young Poet, Rilke\'s correspondence with a young military cadet named Franz Kappus who wrote asking for advice about whether to become a poet. Rilke\'s answer unfolds over 10 letters and is one of the most generous acts in literary history. This passage argues against the impatience for resolution — the anxiety to have the answers, to know what to do, to have it settled. The questions themselves — about love, vocation, meaning, God — are not obstacles to living. They are the texture of a life genuinely engaged with its own depth.',
    why: 'The tolerance for uncertainty — what psychologists call ambiguity tolerance — is strongly associated with creative and intellectual flourishing. People who need resolution quickly tend to foreclose on richer possibilities. Rilke is counseling a deliberate cultivation of openness, not a passive waiting.',
  },
  'The only journey is the journey within.': {
    meaning: 'Rilke wrote this in Letters to a Young Poet. He is not dismissing external travel or experience — he is pointing out that the transformations that matter most happen internally, and that all the external experience in the world will not change a person who has not done the interior work. The journey within is not a retreat from the world; it is the prerequisite for genuinely encountering it.',
    why: 'Contemplative traditions from Zen to Christian mysticism to Stoicism are unanimous on this point: wisdom does not come from accumulation of external experience but from the quality of attention brought to any experience. The same event — a loss, a failure, an encounter — is transformative for one person and merely inconvenient for another, depending entirely on interior resources.',
  },
  // Jung
  'Who looks outside, dreams; who looks inside, awakes.': {
    meaning: 'Jung wrote this in a letter. The "dreaming" is not passive sleep but the active confusion of projection with reality — attributing to the external world qualities that are actually features of one\'s own psychology. We see enemies where we fear our own aggression; we see potential saviors where we have disowned our own strength. Looking inside — the sustained, honest examination of one\'s own unconscious — is what breaks this spell. Awakening, in Jung\'s sense, is not a single event but an ongoing practice of claiming what has been projected outward.',
    why: 'This is the foundation of depth psychology and much of what became cognitive-behavioral therapy: the realization that our suffering is often generated by the way we perceive and interpret reality, not by reality itself. The process of bringing unconscious patterns into consciousness — through therapy, journaling, serious relationships, creative work — is one of the most powerful interventions available to a human being.',
  },
  'Until you make the unconscious conscious, it will direct your life and you will call it fate.': {
    meaning: 'This is one of Jung\'s most quoted insights. The unconscious mind — everything we have repressed, denied, projected, or simply never examined — does not disappear when we avoid it. It operates, from below, shaping our choices, reactions, and patterns in ways we can\'t see. We then experience these patterns as external forces — fate, bad luck, the inexplicable tendency to end up in the same kinds of situations. Making the unconscious conscious is the process of reclaiming authorship of one\'s own life.',
    why: 'Modern neuroscience has confirmed that most mental processing is non-conscious. The question Jung raises is not whether this is true but what to do about it. Psychotherapy, meditation, serious self-reflection, and honest relationship all serve the function he describes: bringing the hidden patterns into light where they can be examined and changed.',
  },
  // Frankl
  'Between stimulus and response there is a space. In that space is our power to choose our response.': {
    meaning: 'This formulation — often misattributed, but rooted in Frankl\'s logotherapy — describes the fundamental capacity that distinguishes human consciousness from purely mechanical response. Animals respond to stimuli with programmed behaviors; humans, uniquely, have the ability to pause between stimulus and response and choose. This pause — which can be microseconds or a deliberate practice of years — is where character, freedom, and growth live. In the concentration camps, Frankl observed this in the extreme: people whose choices were reduced to almost nothing still retained this final freedom.',
    why: 'This concept is the foundation of most modern therapy: cognitive behavioral therapy, dialectical behavior therapy, and mindfulness practice all work by expanding the space between trigger and response. The practice is simple to describe and genuinely difficult: to notice the impulse before acting on it, and to choose rather than react.',
  },
  'Those who have a why to live can bear almost any how.': {
    meaning: 'Frankl adapted this from Nietzsche and made it central to logotherapy. In Auschwitz, he observed that the prisoners who survived psychologically were not those with the strongest bodies or the least suffering, but those who maintained a sense that their lives had meaning — that someone was waiting for them, that they had something to complete, that their experience would one day serve a purpose. Purpose functions as a buffer against despair: if the suffering is in service of something, it becomes endurable in a way that random suffering is not.',
    why: 'Empirical research consistently finds that people with a strong sense of purpose live longer, recover faster from illness, resist depression more effectively, and report higher life satisfaction. The mechanism is not simply hope — it is the cognitive integration of difficulty into a larger narrative that gives it meaning.',
  },
  // Rumi
  'Out beyond ideas of wrongdoing and rightdoing, there is a field. I will meet you there.': {
    meaning: 'This is from the Divan-e Shams, Rumi\'s massive collection of Persian poetry dedicated to his beloved teacher Shams of Tabriz. The field beyond wrongdoing and rightdoing is a mystical concept: the place beyond moral categories, beyond judgment and counter-judgment, where two souls can meet in their essence rather than their positions. It is an invitation to encounter — not to abandon moral thinking, but to recognize that genuine meeting requires going beyond the defensive arguments with which we normally protect ourselves.',
    why: 'The most intractable conflicts — political, religious, personal — are conducted entirely within the space of "wrongdoing and rightdoing," where each party is primarily defending their own moral position. Rumi\'s invitation points to the possibility of encounter that goes beneath the positions to the people holding them. This is the foundation of genuine dialogue.',
  },
  'What you seek is seeking you.': {
    meaning: 'This is one of Rumi\'s most enigmatic and beloved lines. He is describing the mystical understanding that desire and its object are not separate: the longing for God (or love, or truth) is itself the beginning of the encounter with what is longed for. The search is not separate from the find — the very fact of being drawn toward something is evidence of a relationship already in motion. This is not magical thinking; it is an observation about the structure of attention and resonance.',
    why: 'This has practical applications beyond mysticism: the things we are genuinely drawn to — the problems that fascinate, the people who move us, the questions that won\'t leave us alone — are often indicators of where our deepest capacities lie. Attention follows something before the conscious mind articulates why. Learning to trust that pull is a skill.',
  },
  // Lao Tzu
  'Nature does not hurry, yet everything is accomplished.': {
    meaning: 'This is a central teaching of the Tao Te Ching. Lao Tzu is pointing to the way the natural world operates: without goal-setting, without schedules, without urgency — and yet the seasons turn, seeds germinate, rivers find the sea. The underlying principle — the Tao — accomplishes everything through wu wei: non-forcing, effortless action aligned with the nature of things. The lesson is not passivity but the recognition that forcing accelerates some things while distorting or preventing others.',
    why: 'The modern urgency culture — the productivity apps, the hustle ideology, the compulsion to do more faster — is producing measurable dysfunction: burnout, anxiety, a pervasive sense that one is always behind. Lao Tzu\'s observation is that the most sustainable and often the most effective action is the kind that works with the grain of the situation rather than against it.',
  },
  // Default
};

function getMeaning(text: string): { meaning: string; why: string } | null {
  // Try exact match first
  for (const key of Object.keys(QUOTE_MEANINGS)) {
    if (text.startsWith(key) || text === key) return QUOTE_MEANINGS[key];
  }
  return null;
}

function buildContext(
  card: { id: string; text: string; author: string; domain: string; era: string; sub_domain: string }
): { historical_context: string; meaning: string; why_it_matters: string } | null {
  const authorContext = AUTHOR_CONTEXT[card.author];
  const quoteMeaning = getMeaning(card.text);

  if (!authorContext && !quoteMeaning) return null;

  return {
    historical_context: authorContext ?? `${card.author} was a ${card.era ?? ''} ${card.domain ?? 'thinker'} whose work continues to shape how we understand ${card.sub_domain ?? 'the human condition'}.`,
    meaning: quoteMeaning?.meaning ?? `This statement by ${card.author} invites reflection on ${card.domain === 'philosophy' ? 'the nature of the examined life' : card.domain === 'psychology' ? 'the inner workings of the human mind' : 'what it means to live well'}.`,
    why_it_matters: quoteMeaning?.why ?? `${card.author}'s insight remains as relevant today as when it was first expressed — a reminder that the fundamental questions of how to live, think, and act do not change with technology or culture.`,
  };
}

async function main() {
  const args = process.argv.slice(2);
  const reload = args.includes('--reload');
  const authorFilter = args.includes('--author') ? args[args.indexOf('--author') + 1] : null;

  console.log('=== Context Generation ===\n');

  let query = supabase
    .from('specimen_cards')
    .select('id, text, author, domain, era, sub_domain')
    .eq('is_active', true);

  if (!reload) query = query.eq('context_loaded', false);
  if (authorFilter) query = query.eq('author', authorFilter);

  const { data: cards, error } = await query;
  if (error || !cards) { console.error('Failed:', error); return; }

  console.log(`Processing ${cards.length} cards...\n`);

  let loaded = 0, skipped = 0;

  for (const card of cards) {
    const ctx = buildContext(card as { id: string; text: string; author: string; domain: string; era: string; sub_domain: string });

    if (!ctx) {
      skipped++;
      continue;
    }

    const { error: err } = await supabase
      .from('specimen_cards')
      .update({ ...ctx, context_loaded: true })
      .eq('id', card.id);

    if (err) {
      console.error(`Error on ${card.id}:`, err.message);
    } else {
      loaded++;
    }
  }

  console.log(`✓ ${loaded} cards enriched with context`);
  console.log(`  ${skipped} cards skipped (no context available yet)`);
  console.log(`\nTo add more context, add entries to AUTHOR_CONTEXT and QUOTE_MEANINGS in this file.`);
}

main().catch(console.error);
