import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';
import { createHash } from 'crypto';

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_KEY!
);

function id(author: string, text: string) {
  const slug = author.toLowerCase().replace(/[^a-z0-9]/g, '-').slice(0, 20);
  const hash = createHash('sha1').update(text.slice(0, 50)).digest('hex').slice(0, 8);
  return `${slug}-${hash}`;
}

const cards = [
  // ── PHILOSOPHY / STOICISM ────────────────────────────────────────────────────
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", author_title: "Roman Emperor & Stoic Philosopher", domain: "philosophy", sub_domain: "stoicism", era: "ancient", source: "Meditations", themes: ["control","resilience","mind"], archetype_affinity: ["hero","sage"] },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius", author_title: "Roman Emperor & Stoic Philosopher", domain: "philosophy", sub_domain: "stoicism", era: "ancient", source: "Meditations", themes: ["obstacles","growth","transformation"], archetype_affinity: ["hero","sage"] },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius", author_title: "Roman Emperor & Stoic Philosopher", domain: "philosophy", sub_domain: "stoicism", era: "ancient", source: "Meditations", themes: ["action","virtue","integrity"], archetype_affinity: ["hero","sage"] },
  { text: "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.", author: "Marcus Aurelius", author_title: "Roman Emperor & Stoic Philosopher", domain: "philosophy", sub_domain: "stoicism", era: "ancient", source: "Meditations", themes: ["presence","anxiety","reason"], archetype_affinity: ["hero","sage"] },
  { text: "Loss is nothing else but change, and change is Nature's delight.", author: "Marcus Aurelius", author_title: "Roman Emperor & Stoic Philosopher", domain: "philosophy", sub_domain: "stoicism", era: "ancient", source: "Meditations", themes: ["change","loss","nature"], archetype_affinity: ["mystic","sage"] },

  { text: "Nusquam est qui ubique est — He who is everywhere is nowhere.", author: "Seneca", author_title: "Roman Stoic Philosopher", domain: "philosophy", sub_domain: "stoicism", era: "ancient", source: "Letters to Lucilius", themes: ["focus","presence","depth"], archetype_affinity: ["sage","mystic"] },
  { text: "Omnia aliena sunt, tempus tantum nostrum est — Everything is alien to us; time alone is ours.", author: "Seneca", author_title: "Roman Stoic Philosopher", domain: "philosophy", sub_domain: "stoicism", era: "ancient", source: "Letters to Lucilius", themes: ["time","ownership","mortality"], archetype_affinity: ["sage","hero"] },
  { text: "Dum differtur vita transcurrit — While we are postponing, life speeds by.", author: "Seneca", author_title: "Roman Stoic Philosopher", domain: "philosophy", sub_domain: "stoicism", era: "ancient", source: "On the Shortness of Life", themes: ["urgency","time","procrastination"], archetype_affinity: ["hero","sage"] },
  { text: "The whole future lies in uncertainty: live immediately.", author: "Seneca", author_title: "Roman Stoic Philosopher", domain: "philosophy", sub_domain: "stoicism", era: "ancient", source: "On the Shortness of Life", themes: ["presence","uncertainty","living"], archetype_affinity: ["hero","explorer"] },
  { text: "No man was ever wise by chance.", author: "Seneca", author_title: "Roman Stoic Philosopher", domain: "philosophy", sub_domain: "stoicism", era: "ancient", source: "Letters to Lucilius", themes: ["wisdom","intentionality","practice"], archetype_affinity: ["sage","hero"] },

  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus", author_title: "Greek Stoic Philosopher", domain: "philosophy", sub_domain: "stoicism", era: "ancient", source: "Enchiridion", themes: ["control","acceptance","agency"], archetype_affinity: ["hero","sage"] },
  { text: "Men are disturbed not by the things which happen, but by the opinions about the things.", author: "Epictetus", author_title: "Greek Stoic Philosopher", domain: "philosophy", sub_domain: "stoicism", era: "ancient", source: "Enchiridion", themes: ["perception","mind","suffering"], archetype_affinity: ["sage","hero"] },
  { text: "Seek not the good in external things; seek it in yourself.", author: "Epictetus", author_title: "Greek Stoic Philosopher", domain: "philosophy", sub_domain: "stoicism", era: "ancient", source: "Discourses", themes: ["inner-life","virtue","self-knowledge"], archetype_affinity: ["sage","mystic"] },
  { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus", author_title: "Greek Stoic Philosopher", domain: "philosophy", sub_domain: "stoicism", era: "ancient", source: "Discourses", themes: ["identity","action","intention"], archetype_affinity: ["hero","creator"] },

  // ── PHILOSOPHY / EXISTENTIALISM ──────────────────────────────────────────────
  { text: "In the midst of winter, I found there was, within me, an invincible summer.", author: "Albert Camus", author_title: "French Philosopher & Nobel Laureate", domain: "philosophy", sub_domain: "absurdism", era: "modern", source: "Return to Tipasa", themes: ["resilience","inner-strength","winter"], archetype_affinity: ["rebel","hero"] },
  { text: "One must imagine Sisyphus happy.", author: "Albert Camus", author_title: "French Philosopher & Nobel Laureate", domain: "philosophy", sub_domain: "absurdism", era: "modern", source: "The Myth of Sisyphus", themes: ["absurdism","joy","meaning"], archetype_affinity: ["rebel","mystic"] },
  { text: "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.", author: "Albert Camus", author_title: "French Philosopher & Nobel Laureate", domain: "philosophy", sub_domain: "absurdism", era: "modern", themes: ["freedom","rebellion","existence"], archetype_affinity: ["rebel","explorer"] },
  { text: "Real generosity towards the future lies in giving all to the present.", author: "Albert Camus", author_title: "French Philosopher & Nobel Laureate", domain: "philosophy", sub_domain: "absurdism", era: "modern", source: "The Rebel", themes: ["generosity","presence","future"], archetype_affinity: ["lover","caregiver"] },
  { text: "Do not wait for the last judgment — it takes place every day.", author: "Albert Camus", author_title: "French Philosopher & Nobel Laureate", domain: "philosophy", sub_domain: "absurdism", era: "modern", source: "The Fall", themes: ["accountability","daily-life","judgment"], archetype_affinity: ["rebel","sage"] },

  { text: "We are condemned to be free.", author: "Jean-Paul Sartre", author_title: "French Existentialist Philosopher", domain: "philosophy", sub_domain: "existentialism", era: "modern", source: "Being and Nothingness", themes: ["freedom","responsibility","existence"], archetype_affinity: ["rebel","explorer"] },
  { text: "Existence precedes essence.", author: "Jean-Paul Sartre", author_title: "French Existentialist Philosopher", domain: "philosophy", sub_domain: "existentialism", era: "modern", source: "Existentialism Is a Humanism", themes: ["identity","becoming","existence"], archetype_affinity: ["rebel","creator"] },
  { text: "Hell is other people.", author: "Jean-Paul Sartre", author_title: "French Existentialist Philosopher", domain: "philosophy", sub_domain: "existentialism", era: "modern", source: "No Exit", themes: ["others","consciousness","conflict"], archetype_affinity: ["rebel","mystic"] },
  { text: "Freedom is what you do with what's been done to you.", author: "Jean-Paul Sartre", author_title: "French Existentialist Philosopher", domain: "philosophy", sub_domain: "existentialism", era: "modern", themes: ["freedom","agency","past"], archetype_affinity: ["rebel","hero"] },

  { text: "Life can only be understood backwards; but it must be lived forwards.", author: "Søren Kierkegaard", author_title: "Danish Philosopher & Theologian", domain: "philosophy", sub_domain: "existentialism", era: "modern", source: "Journals", themes: ["time","understanding","living"], archetype_affinity: ["mystic","sage"] },
  { text: "The most common form of despair is not being who you are.", author: "Søren Kierkegaard", author_title: "Danish Philosopher & Theologian", domain: "philosophy", sub_domain: "existentialism", era: "modern", source: "The Sickness Unto Death", themes: ["authenticity","despair","identity"], archetype_affinity: ["rebel","explorer"] },
  { text: "The function of prayer is not to influence God, but rather to change the nature of the one who prays.", author: "Søren Kierkegaard", author_title: "Danish Philosopher & Theologian", domain: "philosophy", sub_domain: "existentialism", era: "modern", themes: ["prayer","transformation","self"], archetype_affinity: ["mystic","sage"] },
  { text: "Boredom is the root of all evil — the despairing refusal to be oneself.", author: "Søren Kierkegaard", author_title: "Danish Philosopher & Theologian", domain: "philosophy", sub_domain: "existentialism", era: "modern", source: "Either/Or", themes: ["boredom","authenticity","despair"], archetype_affinity: ["rebel","explorer"] },

  { text: "One is not born, but rather becomes, a woman.", author: "Simone de Beauvoir", author_title: "French Existentialist Philosopher", domain: "philosophy", sub_domain: "feminism", era: "modern", source: "The Second Sex", themes: ["identity","becoming","gender"], archetype_affinity: ["rebel","explorer"] },
  { text: "To catch a husband is an art; to hold him is a job.", author: "Simone de Beauvoir", author_title: "French Existentialist Philosopher", domain: "philosophy", sub_domain: "feminism", era: "modern", source: "The Second Sex", themes: ["relationships","power","society"], archetype_affinity: ["rebel","sage"] },
  { text: "I am awfully greedy; I want everything from life.", author: "Simone de Beauvoir", author_title: "French Existentialist Philosopher", domain: "philosophy", sub_domain: "feminism", era: "modern", source: "Letters to Sartre", themes: ["desire","fullness","living"], archetype_affinity: ["explorer","lover"] },
  { text: "Change your life today. Don't gamble on the future, act now, without delay.", author: "Simone de Beauvoir", author_title: "French Existentialist Philosopher", domain: "philosophy", sub_domain: "feminism", era: "modern", themes: ["action","urgency","change"], archetype_affinity: ["hero","rebel"] },

  { text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche", author_title: "German Philosopher", domain: "philosophy", sub_domain: "existentialism", era: "modern", source: "Twilight of the Idols", themes: ["music","beauty","life"], archetype_affinity: ["creator","lover"] },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche", author_title: "German Philosopher", domain: "philosophy", sub_domain: "existentialism", era: "modern", source: "Twilight of the Idols", themes: ["resilience","adversity","strength"], archetype_affinity: ["hero","rebel"] },
  { text: "The higher we soar, the smaller we appear to those who cannot fly.", author: "Friedrich Nietzsche", author_title: "German Philosopher", domain: "philosophy", sub_domain: "existentialism", era: "modern", source: "Thus Spoke Zarathustra", themes: ["greatness","perspective","solitude"], archetype_affinity: ["creator","rebel"] },
  { text: "There are no facts, only interpretations.", author: "Friedrich Nietzsche", author_title: "German Philosopher", domain: "philosophy", sub_domain: "existentialism", era: "modern", source: "Notebooks", themes: ["truth","perspective","reality"], archetype_affinity: ["sage","rebel"] },
  { text: "One must still have chaos in oneself to be able to give birth to a dancing star.", author: "Friedrich Nietzsche", author_title: "German Philosopher", domain: "philosophy", sub_domain: "existentialism", era: "modern", source: "Thus Spoke Zarathustra", themes: ["creativity","chaos","potential"], archetype_affinity: ["creator","rebel"] },

  // ── PHILOSOPHY / ANCIENT ─────────────────────────────────────────────────────
  { text: "The unexamined life is not worth living.", author: "Socrates", author_title: "Greek Philosopher", domain: "philosophy", sub_domain: "dialectics", era: "ancient", source: "Apology", themes: ["self-knowledge","examined-life","virtue"], archetype_affinity: ["sage","rebel"] },
  { text: "I know that I know nothing.", author: "Socrates", author_title: "Greek Philosopher", domain: "philosophy", sub_domain: "dialectics", era: "ancient", themes: ["humility","wisdom","ignorance"], archetype_affinity: ["sage","mystic"] },
  { text: "To know thyself is the beginning of wisdom.", author: "Socrates", author_title: "Greek Philosopher", domain: "philosophy", sub_domain: "dialectics", era: "ancient", themes: ["self-knowledge","wisdom","beginning"], archetype_affinity: ["sage","mystic"] },
  { text: "Strong minds discuss ideas, average minds discuss events, weak minds discuss people.", author: "Socrates", author_title: "Greek Philosopher", domain: "philosophy", sub_domain: "dialectics", era: "ancient", themes: ["ideas","mind","character"], archetype_affinity: ["sage","creator"] },

  { text: "We are what we repeatedly do. Excellence, then, is not an act but a habit.", author: "Aristotle", author_title: "Greek Philosopher, 384–322 BC", domain: "philosophy", sub_domain: "ethics", era: "ancient", source: "Nicomachean Ethics", themes: ["habit","excellence","virtue"], archetype_affinity: ["hero","sage"] },
  { text: "The whole is greater than the sum of its parts.", author: "Aristotle", author_title: "Greek Philosopher, 384–322 BC", domain: "philosophy", sub_domain: "ethics", era: "ancient", source: "Metaphysics", themes: ["wholeness","system","unity"], archetype_affinity: ["sage","creator"] },
  { text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle", author_title: "Greek Philosopher, 384–322 BC", domain: "philosophy", sub_domain: "ethics", era: "ancient", source: "Nicomachean Ethics", themes: ["education","open-mindedness","thought"], archetype_affinity: ["sage","explorer"] },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", author_title: "Greek Philosopher, 384–322 BC", domain: "philosophy", sub_domain: "ethics", era: "ancient", themes: ["self-knowledge","wisdom","beginning"], archetype_affinity: ["sage","mystic"] },

  { text: "At the touch of love, everyone becomes a poet.", author: "Plato", author_title: "Greek Philosopher, 428–348 BC", domain: "philosophy", sub_domain: "idealism", era: "ancient", source: "The Symposium", themes: ["love","beauty","transformation"], archetype_affinity: ["lover","creator"] },
  { text: "Beauty lies in the eyes of the beholder.", author: "Plato", author_title: "Greek Philosopher, 428–348 BC", domain: "philosophy", sub_domain: "idealism", era: "ancient", themes: ["beauty","perception","subjectivity"], archetype_affinity: ["lover","mystic"] },
  { text: "Courage is knowing what not to fear.", author: "Plato", author_title: "Greek Philosopher, 428–348 BC", domain: "philosophy", sub_domain: "idealism", era: "ancient", source: "Protagoras", themes: ["courage","fear","discernment"], archetype_affinity: ["hero","sage"] },
  { text: "Wise men speak because they have something to say; fools because they have to say something.", author: "Plato", author_title: "Greek Philosopher, 428–348 BC", domain: "philosophy", sub_domain: "idealism", era: "ancient", themes: ["wisdom","silence","speech"], archetype_affinity: ["sage","mystic"] },

  // ── PHILOSOPHY / EASTERN ─────────────────────────────────────────────────────
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu", author_title: "Ancient Chinese Philosopher, Tao Te Ching", domain: "philosophy", sub_domain: "taoism", era: "ancient", source: "Tao Te Ching", themes: ["patience","flow","naturalness"], archetype_affinity: ["mystic","sage"] },
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu", author_title: "Ancient Chinese Philosopher, Tao Te Ching", domain: "philosophy", sub_domain: "taoism", era: "ancient", source: "Tao Te Ching", themes: ["beginning","journey","action"], archetype_affinity: ["hero","explorer"] },
  { text: "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power.", author: "Lao Tzu", author_title: "Ancient Chinese Philosopher, Tao Te Ching", domain: "philosophy", sub_domain: "taoism", era: "ancient", source: "Tao Te Ching", themes: ["self-knowledge","wisdom","power"], archetype_affinity: ["sage","mystic"] },
  { text: "When you realize there is nothing lacking, the whole world belongs to you.", author: "Lao Tzu", author_title: "Ancient Chinese Philosopher, Tao Te Ching", domain: "philosophy", sub_domain: "taoism", era: "ancient", source: "Tao Te Ching", themes: ["abundance","contentment","wholeness"], archetype_affinity: ["mystic","sage"] },
  { text: "Silence is a source of great strength.", author: "Lao Tzu", author_title: "Ancient Chinese Philosopher, Tao Te Ching", domain: "philosophy", sub_domain: "taoism", era: "ancient", source: "Tao Te Ching", themes: ["silence","strength","stillness"], archetype_affinity: ["mystic","sage"] },

  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", author_title: "Chinese Philosopher & Teacher", domain: "philosophy", sub_domain: "confucianism", era: "ancient", themes: ["persistence","progress","endurance"], archetype_affinity: ["hero","sage"] },
  { text: "The man who asks a question is a fool for a minute; the man who does not ask is a fool for life.", author: "Confucius", author_title: "Chinese Philosopher & Teacher", domain: "philosophy", sub_domain: "confucianism", era: "ancient", themes: ["curiosity","learning","humility"], archetype_affinity: ["sage","explorer"] },
  { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius", author_title: "Chinese Philosopher & Teacher", domain: "philosophy", sub_domain: "confucianism", era: "ancient", themes: ["simplicity","complexity","clarity"], archetype_affinity: ["sage","mystic"] },
  { text: "The superior man is satisfied and composed; the mean man is always full of distress.", author: "Confucius", author_title: "Chinese Philosopher & Teacher", domain: "philosophy", sub_domain: "confucianism", era: "ancient", source: "Analects", themes: ["equanimity","character","peace"], archetype_affinity: ["sage","hero"] },

  { text: "The fish trap exists because of the fish. Once you have gotten the fish, you can forget the trap.", author: "Zhuangzi", author_title: "Ancient Chinese Philosopher", domain: "philosophy", sub_domain: "taoism", era: "ancient", source: "Zhuangzi", themes: ["means","ends","letting-go"], archetype_affinity: ["mystic","explorer"] },
  { text: "I do not know whether I was then a man dreaming I was a butterfly, or whether I am now a butterfly dreaming I am a man.", author: "Zhuangzi", author_title: "Ancient Chinese Philosopher", domain: "philosophy", sub_domain: "taoism", era: "ancient", source: "Zhuangzi", themes: ["reality","dreams","identity"], archetype_affinity: ["mystic","explorer"] },
  { text: "Flow with whatever may happen, and let your mind be free: stay centered by accepting whatever you are doing.", author: "Zhuangzi", author_title: "Ancient Chinese Philosopher", domain: "philosophy", sub_domain: "taoism", era: "ancient", source: "Zhuangzi", themes: ["flow","acceptance","freedom"], archetype_affinity: ["mystic","explorer"] },

  // ── PSYCHOLOGY ───────────────────────────────────────────────────────────────
  { text: "Who looks outside, dreams; who looks inside, awakes.", author: "Carl Jung", author_title: "Swiss Psychiatrist & Psychoanalyst", domain: "psychology", sub_domain: "analytical psychology", era: "modern", themes: ["inner-life","consciousness","awakening"], archetype_affinity: ["mystic","sage"] },
  { text: "The privilege of a lifetime is to become who you truly are.", author: "Carl Jung", author_title: "Swiss Psychiatrist & Psychoanalyst", domain: "psychology", sub_domain: "analytical psychology", era: "modern", themes: ["authenticity","individuation","becoming"], archetype_affinity: ["explorer","mystic"] },
  { text: "Everything that irritates us about others can lead us to an understanding of ourselves.", author: "Carl Jung", author_title: "Swiss Psychiatrist & Psychoanalyst", domain: "psychology", sub_domain: "analytical psychology", era: "modern", themes: ["shadow","projection","self-knowledge"], archetype_affinity: ["sage","mystic"] },
  { text: "Until you make the unconscious conscious, it will direct your life and you will call it fate.", author: "Carl Jung", author_title: "Swiss Psychiatrist & Psychoanalyst", domain: "psychology", sub_domain: "analytical psychology", era: "modern", themes: ["unconscious","consciousness","fate"], archetype_affinity: ["mystic","sage"] },
  { text: "Your visions will become clear only when you can look into your own heart.", author: "Carl Jung", author_title: "Swiss Psychiatrist & Psychoanalyst", domain: "psychology", sub_domain: "analytical psychology", era: "modern", themes: ["vision","heart","clarity"], archetype_affinity: ["mystic","creator"] },

  { text: "Between stimulus and response there is a space. In that space is our power to choose our response.", author: "Viktor Frankl", author_title: "Austrian Psychiatrist & Holocaust Survivor", domain: "psychology", sub_domain: "logotherapy", era: "modern", source: "Man's Search for Meaning", themes: ["freedom","choice","agency"], archetype_affinity: ["sage","hero"] },
  { text: "Those who have a why to live can bear almost any how.", author: "Viktor Frankl", author_title: "Austrian Psychiatrist & Holocaust Survivor", domain: "psychology", sub_domain: "logotherapy", era: "modern", source: "Man's Search for Meaning", themes: ["meaning","purpose","resilience"], archetype_affinity: ["hero","mystic"] },
  { text: "When we are no longer able to change a situation, we are challenged to change ourselves.", author: "Viktor Frankl", author_title: "Austrian Psychiatrist & Holocaust Survivor", domain: "psychology", sub_domain: "logotherapy", era: "modern", source: "Man's Search for Meaning", themes: ["change","transformation","acceptance"], archetype_affinity: ["hero","sage"] },
  { text: "The last of human freedoms — to choose one's attitude in any given set of circumstances.", author: "Viktor Frankl", author_title: "Austrian Psychiatrist & Holocaust Survivor", domain: "psychology", sub_domain: "logotherapy", era: "modern", source: "Man's Search for Meaning", themes: ["freedom","attitude","adversity"], archetype_affinity: ["hero","sage"] },

  { text: "Love is an action, never simply a feeling.", author: "bell hooks", author_title: "American Author & Cultural Critic", domain: "psychology", sub_domain: "love", era: "contemporary", source: "All About Love", themes: ["love","action","commitment"], archetype_affinity: ["lover","caregiver"] },
  { text: "Rarely, if ever, are any of us healed in isolation.", author: "bell hooks", author_title: "American Author & Cultural Critic", domain: "psychology", sub_domain: "healing", era: "contemporary", source: "All About Love", themes: ["healing","community","connection"], archetype_affinity: ["caregiver","lover"] },
  { text: "The function of art is to do more than tell it like it is — it is to imagine what is possible.", author: "bell hooks", author_title: "American Author & Cultural Critic", domain: "psychology", sub_domain: "art", era: "contemporary", themes: ["art","possibility","imagination"], archetype_affinity: ["creator","rebel"] },
  { text: "To love well is the task in all meaningful relationships — not just romantic bonds.", author: "bell hooks", author_title: "American Author & Cultural Critic", domain: "psychology", sub_domain: "love", era: "contemporary", source: "All About Love", themes: ["love","relationships","intention"], archetype_affinity: ["lover","caregiver"] },

  { text: "Vulnerability is not winning or losing; it is having the courage to show up and be seen.", author: "Brené Brown", author_title: "American Research Professor & Author", domain: "psychology", sub_domain: "vulnerability research", era: "contemporary", source: "Daring Greatly", themes: ["vulnerability","courage","authenticity"], archetype_affinity: ["lover","hero"] },
  { text: "Owning our story and loving ourselves through that process is the bravest thing we will ever do.", author: "Brené Brown", author_title: "American Research Professor & Author", domain: "psychology", sub_domain: "vulnerability research", era: "contemporary", source: "Daring Greatly", themes: ["story","self-love","courage"], archetype_affinity: ["hero","caregiver"] },
  { text: "Connection is why we are here. It is what gives purpose and meaning to our lives.", author: "Brené Brown", author_title: "American Research Professor & Author", domain: "psychology", sub_domain: "vulnerability research", era: "contemporary", source: "The Gifts of Imperfection", themes: ["connection","meaning","belonging"], archetype_affinity: ["caregiver","lover"] },

  { text: "The good life is a process, not a state of being. It is a direction, not a destination.", author: "Carl Rogers", author_title: "American Psychologist", domain: "psychology", sub_domain: "humanistic psychology", era: "modern", source: "On Becoming a Person", themes: ["growth","process","becoming"], archetype_affinity: ["explorer","creator"] },
  { text: "The curious paradox is that when I accept myself just as I am, then I can change.", author: "Carl Rogers", author_title: "American Psychologist", domain: "psychology", sub_domain: "humanistic psychology", era: "modern", source: "On Becoming a Person", themes: ["acceptance","change","paradox"], archetype_affinity: ["caregiver","mystic"] },
  { text: "What I am is good enough if I would only be it openly.", author: "Carl Rogers", author_title: "American Psychologist", domain: "psychology", sub_domain: "humanistic psychology", era: "modern", source: "On Becoming a Person", themes: ["authenticity","self-acceptance","openness"], archetype_affinity: ["explorer","lover"] },

  { text: "Act as if what you do makes a difference. It does.", author: "William James", author_title: "American Philosopher & Psychologist", domain: "psychology", sub_domain: "pragmatism", era: "modern", themes: ["agency","meaning","action"], archetype_affinity: ["hero","caregiver"] },
  { text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James", author_title: "American Philosopher & Psychologist", domain: "psychology", sub_domain: "pragmatism", era: "modern", themes: ["mind","choice","stress"], archetype_affinity: ["sage","hero"] },
  { text: "Human beings, by changing the inner attitudes of their minds, can change the outer aspects of their lives.", author: "William James", author_title: "American Philosopher & Psychologist", domain: "psychology", sub_domain: "pragmatism", era: "modern", themes: ["mind","change","transformation"], archetype_affinity: ["hero","creator"] },

  { text: "The task we must set for ourselves is not to feel secure, but to be able to tolerate insecurity.", author: "Erich Fromm", author_title: "German Social Psychologist & Philosopher", domain: "psychology", sub_domain: "humanistic psychology", era: "modern", source: "The Sane Society", themes: ["security","courage","tolerance"], archetype_affinity: ["explorer","hero"] },
  { text: "Love is not primarily a relationship to a specific person; it is an attitude, an orientation of character.", author: "Erich Fromm", author_title: "German Social Psychologist & Philosopher", domain: "psychology", sub_domain: "humanistic psychology", era: "modern", source: "The Art of Loving", themes: ["love","character","orientation"], archetype_affinity: ["lover","caregiver"] },
  { text: "Creativity requires the courage to let go of certainties.", author: "Erich Fromm", author_title: "German Social Psychologist & Philosopher", domain: "psychology", sub_domain: "humanistic psychology", era: "modern", source: "The Sane Society", themes: ["creativity","courage","uncertainty"], archetype_affinity: ["creator","rebel"] },

  // ── LITERATURE ───────────────────────────────────────────────────────────────
  { text: "The cradle rocks above an abyss, and common sense tells us that our existence is but a brief crack of light between two eternities of darkness.", author: "Vladimir Nabokov", author_title: "Russian-American Novelist", domain: "literature", sub_domain: "modernism", era: "modern", source: "Speak, Memory", themes: ["mortality","existence","consciousness"], archetype_affinity: ["mystic","sage"] },
  { text: "Literature and butterflies are the two sweetest passions known to man.", author: "Vladimir Nabokov", author_title: "Russian-American Novelist", domain: "literature", sub_domain: "modernism", era: "modern", themes: ["literature","beauty","passion"], archetype_affinity: ["creator","lover"] },

  { text: "The most important things are the hardest to say.", author: "Stephen King", author_title: "American Author", domain: "literature", sub_domain: "fiction", era: "contemporary", source: "The Body", themes: ["truth","language","vulnerability"], archetype_affinity: ["creator","lover"] },
  { text: "Books are a uniquely portable magic.", author: "Stephen King", author_title: "American Author", domain: "literature", sub_domain: "fiction", era: "contemporary", source: "On Writing", themes: ["books","magic","reading"], archetype_affinity: ["creator","mystic"] },

  { text: "You cannot find peace by avoiding life.", author: "Virginia Woolf", author_title: "English Modernist Writer", domain: "literature", sub_domain: "modernism", era: "modern", themes: ["courage","engagement","living"], archetype_affinity: ["hero","explorer"] },
  { text: "You cannot find peace by avoiding life. Virginia Woolf — each moment is the occasion for something.", author: "Virginia Woolf", author_title: "English Modernist Writer", domain: "literature", sub_domain: "modernism", era: "modern", source: "The Waves", themes: ["presence","occasion","living"], archetype_affinity: ["creator","mystic"] },
  { text: "A woman must have money and a room of her own if she is to write fiction.", author: "Virginia Woolf", author_title: "English Modernist Writer", domain: "literature", sub_domain: "modernism", era: "modern", source: "A Room of One's Own", themes: ["independence","creation","freedom"], archetype_affinity: ["rebel","creator"] },
  { text: "Lock up your libraries if you like; but there is no gate, no lock, no bolt that you can set upon the freedom of my mind.", author: "Virginia Woolf", author_title: "English Modernist Writer", domain: "literature", sub_domain: "modernism", era: "modern", source: "A Room of One's Own", themes: ["freedom","mind","resistance"], archetype_affinity: ["rebel","explorer"] },

  { text: "Not everything that is faced can be changed, but nothing can be changed until it is faced.", author: "James Baldwin", author_title: "American Novelist & Activist", domain: "literature", sub_domain: "civil rights literature", era: "modern", themes: ["truth","courage","change"], archetype_affinity: ["rebel","sage"] },
  { text: "Not everything that is faced can be changed. But nothing can be changed until it is faced.", author: "James Baldwin", author_title: "American Novelist & Activist", domain: "literature", sub_domain: "civil rights literature", era: "modern", source: "I Am Not Your Negro", themes: ["confrontation","change","honesty"], archetype_affinity: ["rebel","hero"] },
  { text: "I love America more than any other country in this world, and, exactly for this reason, I insist on the right to criticize her perpetually.", author: "James Baldwin", author_title: "American Novelist & Activist", domain: "literature", sub_domain: "civil rights literature", era: "modern", source: "Notes of a Native Son", themes: ["love","critique","truth"], archetype_affinity: ["rebel","caregiver"] },
  { text: "The most dangerous creation of any society is the man who has nothing to lose.", author: "James Baldwin", author_title: "American Novelist & Activist", domain: "literature", sub_domain: "civil rights literature", era: "modern", source: "The Fire Next Time", themes: ["society","danger","desperation"], archetype_affinity: ["rebel","sage"] },

  { text: "If you have some power, then your job is to empower somebody else.", author: "Toni Morrison", author_title: "American Nobel Laureate Novelist", domain: "literature", sub_domain: "African-American literature", era: "contemporary", themes: ["power","empowerment","responsibility"], archetype_affinity: ["caregiver","rebel"] },
  { text: "If you have some power, then your job is to empower somebody else.", author: "Toni Morrison", author_title: "American Nobel Laureate Novelist", domain: "literature", sub_domain: "African-American literature", era: "contemporary", source: "O Magazine", themes: ["leadership","generosity","community"], archetype_affinity: ["caregiver","hero"] },
  { text: "Make up a story... For our sake and yours forget your name in the street; tell us what the world has been to you in the dark places and in the light.", author: "Toni Morrison", author_title: "American Nobel Laureate Novelist", domain: "literature", sub_domain: "African-American literature", era: "contemporary", source: "Nobel Lecture", themes: ["story","darkness","light"], archetype_affinity: ["creator","mystic"] },
  { text: "There is no time for despair, no place for self-pity, no need for silence, no room for fear.", author: "Toni Morrison", author_title: "American Nobel Laureate Novelist", domain: "literature", sub_domain: "African-American literature", era: "contemporary", themes: ["urgency","courage","voice"], archetype_affinity: ["rebel","hero"] },

  { text: "I am not afraid of storms, for I am learning how to sail my ship.", author: "Louisa May Alcott", author_title: "American Novelist", domain: "literature", sub_domain: "fiction", era: "modern", source: "Little Women", themes: ["courage","learning","resilience"], archetype_affinity: ["hero","explorer"] },
  { text: "I am not afraid of storms, for I am learning how to sail.", author: "Louisa May Alcott", author_title: "American Novelist", domain: "literature", sub_domain: "fiction", era: "modern", source: "Little Women", themes: ["fear","growth","navigation"], archetype_affinity: ["hero","explorer"] },

  // ── POETRY ───────────────────────────────────────────────────────────────────
  { text: "Out beyond ideas of wrongdoing and rightdoing, there is a field. I will meet you there.", author: "Rumi", author_title: "13th-Century Persian Poet & Sufi Mystic", domain: "poetry", sub_domain: "sufism", era: "medieval", themes: ["transcendence","unity","meeting"], archetype_affinity: ["mystic","lover"], language_origin: "Persian" },
  { text: "You were born with wings. Why prefer to crawl through life?", author: "Rumi", author_title: "13th-Century Persian Poet & Sufi Mystic", domain: "poetry", sub_domain: "sufism", era: "medieval", themes: ["potential","freedom","flight"], archetype_affinity: ["explorer","hero"], language_origin: "Persian" },
  { text: "What you seek is seeking you.", author: "Rumi", author_title: "13th-Century Persian Poet & Sufi Mystic", domain: "poetry", sub_domain: "sufism", era: "medieval", themes: ["seeking","calling","destiny"], archetype_affinity: ["mystic","lover"], language_origin: "Persian" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi", author_title: "13th-Century Persian Poet & Sufi Mystic", domain: "poetry", sub_domain: "sufism", era: "medieval", themes: ["wisdom","change","self"], archetype_affinity: ["mystic","sage"], language_origin: "Persian" },
  { text: "Do not be satisfied with the stories that come before you. Unfold your own myth.", author: "Rumi", author_title: "13th-Century Persian Poet & Sufi Mystic", domain: "poetry", sub_domain: "sufism", era: "medieval", themes: ["story","myth","self-creation"], archetype_affinity: ["creator","explorer"], language_origin: "Persian" },

  { text: "Be patient toward all that is unsolved in your heart and try to love the questions themselves.", author: "Rainer Maria Rilke", author_title: "Bohemian-Austrian Poet", domain: "poetry", sub_domain: "symbolism", era: "modern", source: "Letters to a Young Poet", themes: ["patience","questions","becoming"], archetype_affinity: ["sage","mystic"] },
  { text: "I live my life in widening circles that reach out across the world.", author: "Rainer Maria Rilke", author_title: "Bohemian-Austrian Poet", domain: "poetry", sub_domain: "symbolism", era: "modern", source: "Book of Hours", themes: ["expansion","growth","connection"], archetype_affinity: ["explorer","mystic"] },
  { text: "Perhaps all the dragons in our lives are princesses who are only waiting to see us act, just once, with beauty and courage.", author: "Rainer Maria Rilke", author_title: "Bohemian-Austrian Poet", domain: "poetry", sub_domain: "symbolism", era: "modern", source: "Letters to a Young Poet", themes: ["courage","beauty","transformation"], archetype_affinity: ["hero","mystic"] },
  { text: "The only journey is the journey within.", author: "Rainer Maria Rilke", author_title: "Bohemian-Austrian Poet", domain: "poetry", sub_domain: "symbolism", era: "modern", source: "Letters to a Young Poet", themes: ["inner-life","self-discovery","journey"], archetype_affinity: ["mystic","sage"] },
  { text: "Once the realization is accepted that even between the closest human beings infinite distances continue, a wonderful living side by side can grow.", author: "Rainer Maria Rilke", author_title: "Bohemian-Austrian Poet", domain: "poetry", sub_domain: "symbolism", era: "modern", source: "Letters to a Young Poet", themes: ["relationships","space","togetherness"], archetype_affinity: ["lover","mystic"] },

  { text: "Tell me, what is it you plan to do with your one wild and precious life?", author: "Mary Oliver", author_title: "American Poet", domain: "poetry", sub_domain: "nature poetry", era: "contemporary", source: "The Summer Day", themes: ["life","purpose","wildness"], archetype_affinity: ["mystic","explorer"] },
  { text: "You do not have to be good. You do not have to walk on your knees for a hundred miles through the desert repenting.", author: "Mary Oliver", author_title: "American Poet", domain: "poetry", sub_domain: "nature poetry", era: "contemporary", source: "Wild Geese", themes: ["acceptance","goodness","belonging"], archetype_affinity: ["caregiver","rebel"] },
  { text: "Instructions for living a life: Pay attention. Be astonished. Tell about it.", author: "Mary Oliver", author_title: "American Poet", domain: "poetry", sub_domain: "nature poetry", era: "contemporary", themes: ["attention","wonder","storytelling"], archetype_affinity: ["mystic","creator"] },
  { text: "Whoever you are, no matter how lonely, the world offers itself to your imagination.", author: "Mary Oliver", author_title: "American Poet", domain: "poetry", sub_domain: "nature poetry", era: "contemporary", source: "Wild Geese", themes: ["belonging","imagination","world"], archetype_affinity: ["mystic","lover"] },

  { text: "I took a deep breath and listened to the old brag of my heart: I am, I am, I am.", author: "Sylvia Plath", author_title: "American Poet & Novelist", domain: "poetry", sub_domain: "confessional poetry", era: "modern", source: "The Bell Jar", themes: ["existence","identity","aliveness"], archetype_affinity: ["rebel","mystic"] },
  { text: "I am terrified by this dark thing that sleeps in me.", author: "Sylvia Plath", author_title: "American Poet & Novelist", domain: "poetry", sub_domain: "confessional poetry", era: "modern", source: "Elm", themes: ["shadow","fear","depth"], archetype_affinity: ["mystic","rebel"] },
  { text: "I desire the things which will destroy me in the end.", author: "Sylvia Plath", author_title: "American Poet & Novelist", domain: "poetry", sub_domain: "confessional poetry", era: "modern", source: "Journals", themes: ["desire","destruction","intensity"], archetype_affinity: ["rebel","lover"] },

  { text: "Still I rise.", author: "Maya Angelou", author_title: "American Poet & Civil Rights Activist", domain: "poetry", sub_domain: "civil rights poetry", era: "contemporary", source: "Still I Rise", themes: ["resilience","rising","dignity"], archetype_affinity: ["hero","rebel"] },
  { text: "If you are always trying to be normal, you will never know how amazing you can be.", author: "Maya Angelou", author_title: "American Poet & Civil Rights Activist", domain: "poetry", sub_domain: "civil rights poetry", era: "contemporary", themes: ["authenticity","potential","normalcy"], archetype_affinity: ["rebel","creator"] },
  { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou", author_title: "American Poet & Civil Rights Activist", domain: "poetry", sub_domain: "civil rights poetry", era: "contemporary", themes: ["resilience","defeat","persistence"], archetype_affinity: ["hero","caregiver"] },
  { text: "You may not control all the events that happen to you, but you can decide not to be reduced by them.", author: "Maya Angelou", author_title: "American Poet & Civil Rights Activist", domain: "poetry", sub_domain: "civil rights poetry", era: "contemporary", source: "Letter to My Daughter", themes: ["agency","dignity","adversity"], archetype_affinity: ["hero","rebel"] },

  { text: "I carry your heart with me. I carry it in my heart.", author: "E.E. Cummings", author_title: "American Poet", domain: "poetry", sub_domain: "modernism", era: "modern", source: "[i carry your heart with me]", themes: ["love","carrying","union"], archetype_affinity: ["lover","mystic"] },
  { text: "It takes courage to grow up and become who you really are.", author: "E.E. Cummings", author_title: "American Poet", domain: "poetry", sub_domain: "modernism", era: "modern", themes: ["courage","growth","authenticity"], archetype_affinity: ["hero","explorer"] },
  { text: "To be nobody but yourself in a world which is doing its best night and day to make you everybody else means to fight the hardest battle any human being can fight.", author: "E.E. Cummings", author_title: "American Poet", domain: "poetry", sub_domain: "modernism", era: "modern", themes: ["authenticity","identity","resistance"], archetype_affinity: ["rebel","explorer"] },

  // ── SCIENCE ──────────────────────────────────────────────────────────────────
  { text: "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.", author: "Albert Einstein", author_title: "German-American Theoretical Physicist, Nobel Laureate", domain: "science", sub_domain: "physics", era: "modern", themes: ["imagination","knowledge","creativity"], archetype_affinity: ["creator","sage"] },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", author_title: "German-American Theoretical Physicist, Nobel Laureate", domain: "science", sub_domain: "physics", era: "modern", themes: ["failure","experimentation","growth"], archetype_affinity: ["explorer","creator"] },
  { text: "The most beautiful thing we can experience is the mysterious. It is the source of all true art and science.", author: "Albert Einstein", author_title: "German-American Theoretical Physicist, Nobel Laureate", domain: "science", sub_domain: "physics", era: "modern", themes: ["mystery","beauty","wonder"], archetype_affinity: ["mystic","creator"] },
  { text: "Two things are infinite: the universe and human stupidity; and I am not sure about the universe.", author: "Albert Einstein", author_title: "German-American Theoretical Physicist, Nobel Laureate", domain: "science", sub_domain: "physics", era: "modern", themes: ["humility","humor","infinity"], archetype_affinity: ["sage","rebel"] },
  { text: "Look deep into nature, and then you will understand everything better.", author: "Albert Einstein", author_title: "German-American Theoretical Physicist, Nobel Laureate", domain: "science", sub_domain: "physics", era: "modern", themes: ["nature","understanding","observation"], archetype_affinity: ["mystic","explorer"] },

  { text: "The first principle is that you must not fool yourself — and you are the easiest person to fool.", author: "Richard Feynman", author_title: "American Physicist & Nobel Laureate", domain: "science", sub_domain: "physics", era: "modern", source: "Caltech Commencement Address", themes: ["honesty","self-deception","integrity"], archetype_affinity: ["sage","rebel"] },
  { text: "I would rather have questions that cannot be answered than answers that cannot be questioned.", author: "Richard Feynman", author_title: "American Physicist & Nobel Laureate", domain: "science", sub_domain: "physics", era: "modern", themes: ["curiosity","questions","doubt"], archetype_affinity: ["explorer","sage"] },
  { text: "Study hard what interests you the most in the most undisciplined, irreverent, and original manner possible.", author: "Richard Feynman", author_title: "American Physicist & Nobel Laureate", domain: "science", sub_domain: "physics", era: "modern", themes: ["learning","originality","curiosity"], archetype_affinity: ["explorer","creator"] },
  { text: "Physics is like sex: sure, it may give some practical results, but that is not why we do it.", author: "Richard Feynman", author_title: "American Physicist & Nobel Laureate", domain: "science", sub_domain: "physics", era: "modern", themes: ["intrinsic-motivation","joy","science"], archetype_affinity: ["creator","explorer"] },

  { text: "The cosmos is within us. We are made of star-stuff. We are a way for the universe to know itself.", author: "Carl Sagan", author_title: "American Astronomer & Science Communicator", domain: "science", sub_domain: "astronomy", era: "contemporary", source: "Cosmos", themes: ["cosmos","identity","wonder"], archetype_affinity: ["mystic","explorer"] },
  { text: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan", author_title: "American Astronomer & Science Communicator", domain: "science", sub_domain: "astronomy", era: "contemporary", themes: ["discovery","wonder","science"], archetype_affinity: ["explorer","creator"] },
  { text: "We are a way for the cosmos to know itself.", author: "Carl Sagan", author_title: "American Astronomer & Science Communicator", domain: "science", sub_domain: "astronomy", era: "contemporary", source: "Cosmos", themes: ["consciousness","cosmos","meaning"], archetype_affinity: ["mystic","sage"] },
  { text: "Books are proof that humans are capable of working magic.", author: "Carl Sagan", author_title: "American Astronomer & Science Communicator", domain: "science", sub_domain: "astronomy", era: "contemporary", themes: ["books","magic","knowledge"], archetype_affinity: ["mystic","creator"] },

  { text: "I am not afraid of being called a woman. I was not afraid of it before and I am not afraid now.", author: "Marie Curie", author_title: "Polish-French Physicist & Chemist, Dual Nobel Laureate", domain: "science", sub_domain: "physics", era: "modern", themes: ["courage","identity","perseverance"], archetype_affinity: ["hero","rebel"] },
  { text: "Nothing in life is to be feared; it is only to be understood. Now is the time to understand more, so that we may fear less.", author: "Marie Curie", author_title: "Polish-French Physicist & Chemist, Dual Nobel Laureate", domain: "science", sub_domain: "physics", era: "modern", themes: ["fear","understanding","courage"], archetype_affinity: ["hero","sage"] },
  { text: "Be less curious about people and more curious about ideas.", author: "Marie Curie", author_title: "Polish-French Physicist & Chemist, Dual Nobel Laureate", domain: "science", sub_domain: "physics", era: "modern", themes: ["curiosity","ideas","focus"], archetype_affinity: ["sage","creator"] },

  { text: "My goal is simple. It is a complete understanding of the universe, why it is as it is and why it exists at all.", author: "Stephen Hawking", author_title: "British Theoretical Physicist", domain: "science", sub_domain: "cosmology", era: "contemporary", themes: ["understanding","universe","ambition"], archetype_affinity: ["sage","explorer"] },
  { text: "However difficult life may seem, there is always something you can do and succeed at.", author: "Stephen Hawking", author_title: "British Theoretical Physicist", domain: "science", sub_domain: "cosmology", era: "contemporary", themes: ["resilience","possibility","courage"], archetype_affinity: ["hero","caregiver"] },
  { text: "Intelligence is the ability to adapt to change.", author: "Stephen Hawking", author_title: "British Theoretical Physicist", domain: "science", sub_domain: "cosmology", era: "contemporary", themes: ["intelligence","adaptability","change"], archetype_affinity: ["explorer","creator"] },

  // ── ART ──────────────────────────────────────────────────────────────────────
  { text: "I never painted dreams. I painted my own reality.", author: "Frida Kahlo", author_title: "Mexican Surrealist Painter", domain: "art", sub_domain: "surrealism", era: "modern", themes: ["reality","authenticity","creation"], archetype_affinity: ["creator","rebel"] },
  { text: "Feet, what do I need you for when I have wings to fly?", author: "Frida Kahlo", author_title: "Mexican Surrealist Painter", domain: "art", sub_domain: "surrealism", era: "modern", source: "Diary", themes: ["freedom","transcendence","spirit"], archetype_affinity: ["rebel","explorer"] },
  { text: "At the end of the day, we can endure much more than we think we can.", author: "Frida Kahlo", author_title: "Mexican Surrealist Painter", domain: "art", sub_domain: "surrealism", era: "modern", source: "Diary", themes: ["endurance","resilience","strength"], archetype_affinity: ["hero","rebel"] },
  { text: "I used to think I was the strangest person in the world but then I thought, there are so many people in the world, there must be someone just like me.", author: "Frida Kahlo", author_title: "Mexican Surrealist Painter", domain: "art", sub_domain: "surrealism", era: "modern", themes: ["belonging","identity","connection"], archetype_affinity: ["lover","rebel"] },

  { text: "Every child is an artist. The problem is how to remain an artist once we grow up.", author: "Pablo Picasso", author_title: "Spanish Cubist Artist", domain: "art", sub_domain: "cubism", era: "modern", themes: ["creativity","childhood","artist"], archetype_affinity: ["creator","rebel"] },
  { text: "Inspiration exists, but it has to find you working.", author: "Pablo Picasso", author_title: "Spanish Cubist Artist", domain: "art", sub_domain: "cubism", era: "modern", themes: ["inspiration","work","creativity"], archetype_affinity: ["creator","hero"] },
  { text: "The purpose of art is washing the dust of daily life off our souls.", author: "Pablo Picasso", author_title: "Spanish Cubist Artist", domain: "art", sub_domain: "cubism", era: "modern", themes: ["art","soul","cleansing"], archetype_affinity: ["creator","mystic"] },
  { text: "Learn the rules like a pro, so you can break them like an artist.", author: "Pablo Picasso", author_title: "Spanish Cubist Artist", domain: "art", sub_domain: "cubism", era: "modern", themes: ["rules","creativity","mastery"], archetype_affinity: ["creator","rebel"] },

  { text: "I found I could say things with color and shapes that I could not say any other way — things I had no words for.", author: "Georgia O'Keeffe", author_title: "American Modernist Painter", domain: "art", sub_domain: "modernism", era: "modern", themes: ["expression","color","language"], archetype_affinity: ["creator","mystic"] },
  { text: "I decided that if I could paint that flower in a huge scale, you could not ignore its beauty.", author: "Georgia O'Keeffe", author_title: "American Modernist Painter", domain: "art", sub_domain: "modernism", era: "modern", themes: ["scale","beauty","attention"], archetype_affinity: ["creator","rebel"] },
  { text: "To create one's own world takes courage.", author: "Georgia O'Keeffe", author_title: "American Modernist Painter", domain: "art", sub_domain: "modernism", era: "modern", themes: ["creation","courage","world-building"], archetype_affinity: ["creator","hero"] },

  { text: "In the future, everyone will be world-famous for 15 minutes.", author: "Andy Warhol", author_title: "American Pop Artist", domain: "art", sub_domain: "pop art", era: "contemporary", themes: ["fame","future","media"], archetype_affinity: ["creator","rebel"] },
  { text: "Don't think about making art, just get it done. Let everyone else decide if it's good or bad.", author: "Andy Warhol", author_title: "American Pop Artist", domain: "art", sub_domain: "pop art", era: "contemporary", source: "The Andy Warhol Diaries", themes: ["art","action","judgment"], archetype_affinity: ["creator","rebel"] },
  { text: "They always say time changes things, but you actually have to change them yourself.", author: "Andy Warhol", author_title: "American Pop Artist", domain: "art", sub_domain: "pop art", era: "contemporary", source: "The Philosophy of Andy Warhol", themes: ["change","agency","time"], archetype_affinity: ["rebel","creator"] },

  { text: "Art should comfort the disturbed and disturb the comfortable.", author: "Banksy", author_title: "British Street Artist & Political Activist", domain: "art", sub_domain: "street art", era: "contemporary", themes: ["art","disruption","purpose"], archetype_affinity: ["rebel","creator"] },
  { text: "The greatest crimes in the world are not committed by people breaking the rules but by people following the rules.", author: "Banksy", author_title: "British Street Artist & Political Activist", domain: "art", sub_domain: "street art", era: "contemporary", themes: ["rules","conformity","crime"], archetype_affinity: ["rebel","sage"] },
  { text: "Think outside the box, collapse the box, and take a f---ing sharp knife to it.", author: "Banksy", author_title: "British Street Artist & Political Activist", domain: "art", sub_domain: "street art", era: "contemporary", source: "Cut It Out", themes: ["creativity","thinking","freedom"], archetype_affinity: ["rebel","creator"] },

  // ── ARCHITECTURE ─────────────────────────────────────────────────────────────
  { text: "I want people to feel the silence, to feel the power of architecture.", author: "Tadao Ando", author_title: "Japanese Architect, Pritzker Prize Laureate", domain: "architecture", sub_domain: "critical regionalism", era: "contemporary", themes: ["silence","presence","power"], archetype_affinity: ["mystic","creator"] },
  { text: "My goal is to simplify complexity and to make the complex simple.", author: "Tadao Ando", author_title: "Japanese Architect, Pritzker Prize Laureate", domain: "architecture", sub_domain: "critical regionalism", era: "contemporary", themes: ["simplicity","complexity","clarity"], archetype_affinity: ["sage","creator"] },
  { text: "Although I draw from Japan, I give back to the world.", author: "Tadao Ando", author_title: "Japanese Architect, Pritzker Prize Laureate", domain: "architecture", sub_domain: "critical regionalism", era: "contemporary", themes: ["roots","giving","universality"], archetype_affinity: ["creator","caregiver"] },

  { text: "The sun never knew how great it was until it hit the side of a building.", author: "Louis Kahn", author_title: "American Architect", domain: "architecture", sub_domain: "monumentalism", era: "modern", themes: ["light","revelation","beauty"], archetype_affinity: ["creator","mystic"] },
  { text: "Even a brick wants to be something.", author: "Louis Kahn", author_title: "American Architect", domain: "architecture", sub_domain: "monumentalism", era: "modern", themes: ["potential","material","desire"], archetype_affinity: ["creator","mystic"] },
  { text: "A great building must begin with the unmeasurable, pass through measurable means, and in the end must be unmeasurable.", author: "Louis Kahn", author_title: "American Architect", domain: "architecture", sub_domain: "monumentalism", era: "modern", themes: ["mystery","craft","transcendence"], archetype_affinity: ["mystic","creator"] },

  { text: "There are 360 degrees, so why stick to one?", author: "Zaha Hadid", author_title: "Iraqi-British Architect, Pritzker Prize Laureate", domain: "architecture", sub_domain: "deconstructivism", era: "contemporary", themes: ["possibility","freedom","vision"], archetype_affinity: ["creator","rebel"] },
  { text: "Architecture is really about well-being. I think that people want to feel good in a space.", author: "Zaha Hadid", author_title: "Iraqi-British Architect, Pritzker Prize Laureate", domain: "architecture", sub_domain: "deconstructivism", era: "contemporary", themes: ["wellbeing","space","humanity"], archetype_affinity: ["caregiver","creator"] },
  { text: "I don't think that architecture is only about shelter, is only about a very simple enclosure. It should be able to excite you, to calm you, to make you think.", author: "Zaha Hadid", author_title: "Iraqi-British Architect, Pritzker Prize Laureate", domain: "architecture", sub_domain: "deconstructivism", era: "contemporary", themes: ["architecture","emotion","thought"], archetype_affinity: ["creator","mystic"] },

  { text: "Less is more.", author: "Mies van der Rohe", author_title: "German-American Architect", domain: "architecture", sub_domain: "modernism", era: "modern", themes: ["simplicity","restraint","elegance"], archetype_affinity: ["sage","creator"] },
  { text: "God is in the details.", author: "Mies van der Rohe", author_title: "German-American Architect", domain: "architecture", sub_domain: "modernism", era: "modern", themes: ["details","craft","perfection"], archetype_affinity: ["creator","mystic"] },

  { text: "The longer I live, the more beautiful life becomes.", author: "Frank Lloyd Wright", author_title: "American Architect", domain: "architecture", sub_domain: "organic architecture", era: "modern", themes: ["beauty","aging","appreciation"], archetype_affinity: ["lover","mystic"] },
  { text: "Space is the breath of art.", author: "Frank Lloyd Wright", author_title: "American Architect", domain: "architecture", sub_domain: "organic architecture", era: "modern", themes: ["space","breath","art"], archetype_affinity: ["creator","mystic"] },
  { text: "The thing always happens that you really believe in; and the belief in a thing makes it happen.", author: "Frank Lloyd Wright", author_title: "American Architect", domain: "architecture", sub_domain: "organic architecture", era: "modern", themes: ["belief","manifestation","creation"], archetype_affinity: ["creator","hero"] },

  // ── MUSIC ────────────────────────────────────────────────────────────────────
  { text: "Music can change the world because it can change people.", author: "Bono", author_title: "Irish Rock Musician & Activist", domain: "music", sub_domain: "rock", era: "contemporary", themes: ["music","change","people"], archetype_affinity: ["rebel","caregiver"] },
  { text: "Music is the shorthand of emotion.", author: "Leo Tolstoy", author_title: "Russian Novelist & Philosopher", domain: "music", sub_domain: "classical", era: "modern", themes: ["music","emotion","language"], archetype_affinity: ["lover","creator"] },

  { text: "Music gives a soul to the universe, wings to the mind, flight to the imagination, and life to everything.", author: "Plato", author_title: "Greek Philosopher, 428–348 BC", domain: "music", sub_domain: "classical", era: "ancient", themes: ["music","soul","imagination"], archetype_affinity: ["mystic","creator"] },
  { text: "Where words fail, music speaks.", author: "Hans Christian Andersen", author_title: "Danish Author & Poet", domain: "music", sub_domain: "literature", era: "modern", themes: ["music","language","feeling"], archetype_affinity: ["lover","mystic"] },

  { text: "I was born with music inside me. Music was one of my parts — like my ribs, my kidneys, my liver, my heart.", author: "Ray Charles", author_title: "American Musician & Singer", domain: "music", sub_domain: "soul", era: "contemporary", source: "Brother Ray", themes: ["music","identity","soul"], archetype_affinity: ["creator","mystic"] },
  { text: "Hit the note or miss the note, but don't play it in the middle.", author: "Miles Davis", author_title: "American Jazz Musician & Composer", domain: "music", sub_domain: "jazz", era: "modern", themes: ["commitment","risk","artistry"], archetype_affinity: ["creator","rebel"] },
  { text: "In music, silence is more important than sound.", author: "Miles Davis", author_title: "American Jazz Musician & Composer", domain: "music", sub_domain: "jazz", era: "modern", themes: ["silence","music","space"], archetype_affinity: ["mystic","creator"] },
  { text: "Do not fear mistakes. There are none.", author: "Miles Davis", author_title: "American Jazz Musician & Composer", domain: "music", sub_domain: "jazz", era: "modern", themes: ["fear","mistakes","freedom"], archetype_affinity: ["creator","rebel"] },

  { text: "A change is gonna come.", author: "Sam Cooke", author_title: "American Singer & Songwriter", domain: "music", sub_domain: "soul", era: "modern", source: "A Change Is Gonna Come", themes: ["change","hope","civil-rights"], archetype_affinity: ["hero","caregiver"] },
  { text: "The answer, my friend, is blowin' in the wind.", author: "Bob Dylan", author_title: "American Singer-Songwriter & Nobel Laureate", domain: "music", sub_domain: "folk rock", era: "contemporary", source: "Blowin' in the Wind", themes: ["answers","freedom","ambiguity"], archetype_affinity: ["rebel","mystic"] },
  { text: "To live outside the law, you must be honest.", author: "Bob Dylan", author_title: "American Singer-Songwriter & Nobel Laureate", domain: "music", sub_domain: "folk rock", era: "contemporary", source: "Absolutely Sweet Marie", themes: ["honesty","freedom","integrity"], archetype_affinity: ["rebel","explorer"] },

  // ── BUSINESS & LEADERSHIP ────────────────────────────────────────────────────
  { text: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs", author_title: "Co-Founder of Apple Inc.", domain: "business", sub_domain: "technology", era: "contemporary", source: "Stanford Commencement Address", themes: ["work","passion","satisfaction"], archetype_affinity: ["creator","hero"] },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs", author_title: "Co-Founder of Apple Inc.", domain: "business", sub_domain: "technology", era: "contemporary", source: "Stanford Commencement Address", themes: ["hunger","curiosity","growth"], archetype_affinity: ["explorer","creator"] },
  { text: "Design is not just what it looks like and feels like. Design is how it works.", author: "Steve Jobs", author_title: "Co-Founder of Apple Inc.", domain: "business", sub_domain: "technology", era: "contemporary", themes: ["design","function","beauty"], archetype_affinity: ["creator","sage"] },
  { text: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Steve Jobs", author_title: "Co-Founder of Apple Inc.", domain: "business", sub_domain: "technology", era: "contemporary", themes: ["vision","change","courage"], archetype_affinity: ["creator","rebel"] },

  { text: "Price is what you pay. Value is what you get.", author: "Warren Buffett", author_title: "American Investor & Philanthropist", domain: "business", sub_domain: "investing", era: "contemporary", themes: ["value","price","wisdom"], archetype_affinity: ["sage","hero"] },
  { text: "It takes 20 years to build a reputation and five minutes to ruin it.", author: "Warren Buffett", author_title: "American Investor & Philanthropist", domain: "business", sub_domain: "investing", era: "contemporary", themes: ["reputation","character","time"], archetype_affinity: ["sage","hero"] },
  { text: "The most important investment you can make is in yourself.", author: "Warren Buffett", author_title: "American Investor & Philanthropist", domain: "business", sub_domain: "investing", era: "contemporary", themes: ["investment","self-development","growth"], archetype_affinity: ["sage","hero"] },

  { text: "The secret of getting ahead is getting started.", author: "Mark Twain", author_title: "American Humorist & Novelist", domain: "business", sub_domain: "wisdom", era: "modern", themes: ["action","beginning","momentum"], archetype_affinity: ["hero","creator"] },
  { text: "Start with why.", author: "Simon Sinek", author_title: "British-American Author & Motivational Speaker", domain: "business", sub_domain: "leadership", era: "contemporary", source: "Start with Why", themes: ["purpose","leadership","why"], archetype_affinity: ["hero","sage"] },
  { text: "People don't buy what you do; they buy why you do it.", author: "Simon Sinek", author_title: "British-American Author & Motivational Speaker", domain: "business", sub_domain: "leadership", era: "contemporary", source: "Start with Why", themes: ["purpose","belief","leadership"], archetype_affinity: ["caregiver","hero"] },

  { text: "Wealth is the ability to fully experience life.", author: "Henry David Thoreau", author_title: "American Transcendentalist Author", domain: "business", sub_domain: "philosophy", era: "modern", themes: ["wealth","experience","life"], archetype_affinity: ["explorer","mystic"] },
  { text: "You don't need to be right the first time. You need to be better every time.", author: "Naval Ravikant", author_title: "American Entrepreneur & Philosopher", domain: "business", sub_domain: "venture capital", era: "contemporary", themes: ["iteration","improvement","humility"], archetype_affinity: ["sage","creator"] },
  { text: "Earn with your mind, not your time.", author: "Naval Ravikant", author_title: "American Entrepreneur & Philosopher", domain: "business", sub_domain: "venture capital", era: "contemporary", themes: ["leverage","mind","time"], archetype_affinity: ["sage","creator"] },
  { text: "Read what you love until you love to read.", author: "Naval Ravikant", author_title: "American Entrepreneur & Philosopher", domain: "business", sub_domain: "venture capital", era: "contemporary", themes: ["reading","love","curiosity"], archetype_affinity: ["sage","explorer"] },
  { text: "Specific knowledge is knowledge you cannot be trained for. If society can train you, it can train someone else and replace you.", author: "Naval Ravikant", author_title: "American Entrepreneur & Philosopher", domain: "business", sub_domain: "venture capital", era: "contemporary", themes: ["knowledge","uniqueness","value"], archetype_affinity: ["creator","sage"] },

  { text: "Atomic habits: tiny changes, remarkable results.", author: "James Clear", author_title: "American Author of Atomic Habits", domain: "business", sub_domain: "productivity", era: "contemporary", source: "Atomic Habits", themes: ["habits","small-steps","compounding"], archetype_affinity: ["hero","sage"] },
  { text: "You do not rise to the level of your goals. You fall to the level of your systems.", author: "James Clear", author_title: "American Author of Atomic Habits", domain: "business", sub_domain: "productivity", era: "contemporary", source: "Atomic Habits", themes: ["systems","habits","goals"], archetype_affinity: ["hero","sage"] },
  { text: "Every action you take is a vote for the type of person you wish to become.", author: "James Clear", author_title: "American Author of Atomic Habits", domain: "business", sub_domain: "productivity", era: "contemporary", source: "Atomic Habits", themes: ["identity","action","character"], archetype_affinity: ["hero","creator"] },

  // ── SPIRITUALITY ─────────────────────────────────────────────────────────────
  { text: "Peace comes from within. Do not seek it without.", author: "Siddhartha Gautama (The Buddha)", author_title: "Spiritual Teacher & Founder of Buddhism", domain: "spirituality", sub_domain: "buddhism", era: "ancient", themes: ["peace","inner-life","seeking"], archetype_affinity: ["mystic","sage"] },
  { text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Siddhartha Gautama (The Buddha)", author_title: "Spiritual Teacher & Founder of Buddhism", domain: "spirituality", sub_domain: "buddhism", era: "ancient", themes: ["truth","time","revelation"], archetype_affinity: ["sage","mystic"] },
  { text: "You yourself, as much as anybody in the entire universe, deserve your love and affection.", author: "Siddhartha Gautama (The Buddha)", author_title: "Spiritual Teacher & Founder of Buddhism", domain: "spirituality", sub_domain: "buddhism", era: "ancient", themes: ["self-love","compassion","worthiness"], archetype_affinity: ["caregiver","mystic"] },
  { text: "If you light a lamp for someone else it will also brighten your own path.", author: "Siddhartha Gautama (The Buddha)", author_title: "Spiritual Teacher & Founder of Buddhism", domain: "spirituality", sub_domain: "buddhism", era: "ancient", themes: ["giving","generosity","light"], archetype_affinity: ["caregiver","mystic"] },

  { text: "Only when we have inner peace can we have real peace with the world.", author: "Dalai Lama XIV", author_title: "Tibetan Buddhist Spiritual Leader", domain: "spirituality", sub_domain: "buddhism", era: "contemporary", themes: ["inner-peace","world-peace","foundation"], archetype_affinity: ["mystic","caregiver"] },
  { text: "My religion is very simple. My religion is kindness.", author: "Dalai Lama XIV", author_title: "Tibetan Buddhist Spiritual Leader", domain: "spirituality", sub_domain: "buddhism", era: "contemporary", themes: ["kindness","religion","simplicity"], archetype_affinity: ["caregiver","mystic"] },
  { text: "There is no need for temples, no need for complicated philosophy. Our own brain, our own heart is our temple.", author: "Dalai Lama XIV", author_title: "Tibetan Buddhist Spiritual Leader", domain: "spirituality", sub_domain: "buddhism", era: "contemporary", themes: ["simplicity","heart","temple"], archetype_affinity: ["mystic","sage"] },

  { text: "This too shall pass.", author: "Alan Watts", author_title: "British Philosopher & Zen Interpreter", domain: "spirituality", sub_domain: "zen", era: "modern", themes: ["impermanence","acceptance","time"], archetype_affinity: ["mystic","sage"] },
  { text: "The meaning of life is just to be alive. It is so plain and so obvious and so simple.", author: "Alan Watts", author_title: "British Philosopher & Zen Interpreter", domain: "spirituality", sub_domain: "zen", era: "modern", source: "The Culture of Counter-Culture", themes: ["meaning","simplicity","being"], archetype_affinity: ["mystic","sage"] },
  { text: "You are under no obligation to be the same person you were five minutes ago.", author: "Alan Watts", author_title: "British Philosopher & Zen Interpreter", domain: "spirituality", sub_domain: "zen", era: "modern", themes: ["change","identity","freedom"], archetype_affinity: ["explorer","rebel"] },
  { text: "Man suffers only because he takes seriously what the gods made for fun.", author: "Alan Watts", author_title: "British Philosopher & Zen Interpreter", domain: "spirituality", sub_domain: "zen", era: "modern", themes: ["suffering","play","seriousness"], archetype_affinity: ["mystic","rebel"] },

  { text: "Walk as if you are kissing the Earth with your feet.", author: "Thich Nhat Hanh", author_title: "Vietnamese Buddhist Monk & Peace Activist", domain: "spirituality", sub_domain: "buddhism", era: "contemporary", source: "Peace Is Every Step", themes: ["mindfulness","presence","earth"], archetype_affinity: ["mystic","caregiver"] },
  { text: "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", author: "Thich Nhat Hanh", author_title: "Vietnamese Buddhist Monk & Peace Activist", domain: "spirituality", sub_domain: "buddhism", era: "contemporary", source: "Stepping into Freedom", themes: ["impermanence","breath","anchor"], archetype_affinity: ["mystic","sage"] },
  { text: "The most precious gift we can offer anyone is our attention.", author: "Thich Nhat Hanh", author_title: "Vietnamese Buddhist Monk & Peace Activist", domain: "spirituality", sub_domain: "buddhism", era: "contemporary", themes: ["attention","presence","love"], archetype_affinity: ["caregiver","mystic"] },

  { text: "Attention is the rarest and purest form of generosity.", author: "Simone Weil", author_title: "French Philosopher & Mystic", domain: "philosophy", sub_domain: "mysticism", era: "modern", source: "Waiting for God", themes: ["attention","generosity","presence"], archetype_affinity: ["caregiver","sage"] },
  { text: "Grace fills empty spaces, but it can only enter where there is a void to receive it.", author: "Simone Weil", author_title: "French Philosopher & Mystic", domain: "philosophy", sub_domain: "mysticism", era: "modern", source: "Gravity and Grace", themes: ["grace","emptiness","receiving"], archetype_affinity: ["mystic","sage"] },

  // ── ACTIVISM ─────────────────────────────────────────────────────────────────
  { text: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", author: "Martin Luther King Jr.", author_title: "American Civil Rights Leader", domain: "activism", sub_domain: "civil rights", era: "modern", source: "Strength to Love", themes: ["love","darkness","light"], archetype_affinity: ["hero","caregiver"] },
  { text: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr.", author_title: "American Civil Rights Leader", domain: "activism", sub_domain: "civil rights", era: "modern", themes: ["voice","silence","courage"], archetype_affinity: ["rebel","hero"] },
  { text: "Injustice anywhere is a threat to justice everywhere.", author: "Martin Luther King Jr.", author_title: "American Civil Rights Leader", domain: "activism", sub_domain: "civil rights", era: "modern", source: "Letter from Birmingham Jail", themes: ["justice","injustice","solidarity"], archetype_affinity: ["hero","caregiver"] },
  { text: "The time is always right to do what is right.", author: "Martin Luther King Jr.", author_title: "American Civil Rights Leader", domain: "activism", sub_domain: "civil rights", era: "modern", themes: ["urgency","morality","action"], archetype_affinity: ["hero","rebel"] },

  { text: "It always seems impossible until it's done.", author: "Nelson Mandela", author_title: "South African President & Anti-Apartheid Leader", domain: "activism", sub_domain: "anti-apartheid", era: "contemporary", themes: ["possibility","perseverance","achievement"], archetype_affinity: ["hero","rebel"] },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", author_title: "South African President & Anti-Apartheid Leader", domain: "activism", sub_domain: "anti-apartheid", era: "contemporary", themes: ["education","change","power"], archetype_affinity: ["caregiver","hero"] },
  { text: "I learned that courage was not the absence of fear, but the triumph over it.", author: "Nelson Mandela", author_title: "South African President & Anti-Apartheid Leader", domain: "activism", sub_domain: "anti-apartheid", era: "contemporary", source: "Long Walk to Freedom", themes: ["courage","fear","triumph"], archetype_affinity: ["hero","sage"] },

  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi", author_title: "Indian Independence Leader", domain: "activism", sub_domain: "nonviolence", era: "modern", themes: ["change","self","world"], archetype_affinity: ["hero","caregiver"] },
  { text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi", author_title: "Indian Independence Leader", domain: "activism", sub_domain: "nonviolence", era: "modern", themes: ["gentleness","impact","change"], archetype_affinity: ["hero","caregiver"] },
  { text: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi", author_title: "Indian Independence Leader", domain: "activism", sub_domain: "nonviolence", era: "modern", themes: ["persistence","opposition","victory"], archetype_affinity: ["rebel","hero"] },

  // ── FILM ─────────────────────────────────────────────────────────────────────
  { text: "Every frame is a painting.", author: "Akira Kurosawa", author_title: "Japanese Film Director", domain: "film", sub_domain: "art cinema", era: "modern", themes: ["composition","art","cinema"], archetype_affinity: ["creator","mystic"] },
  { text: "In order to make films, you first need to be a human being.", author: "Akira Kurosawa", author_title: "Japanese Film Director", domain: "film", sub_domain: "art cinema", era: "modern", themes: ["humanity","art","authenticity"], archetype_affinity: ["creator","caregiver"] },

  { text: "A film is — or should be — more like music than like fiction. It should be a progression of moods and feelings.", author: "Stanley Kubrick", author_title: "American Film Director", domain: "film", sub_domain: "art cinema", era: "contemporary", themes: ["film","music","feeling"], archetype_affinity: ["creator","mystic"] },
  { text: "If you can talk brilliantly about a problem, it can create the consoling illusion that it has been mastered.", author: "Stanley Kubrick", author_title: "American Film Director", domain: "film", sub_domain: "art cinema", era: "contemporary", themes: ["talk","action","illusion"], archetype_affinity: ["sage","rebel"] },

  { text: "I want to make films about things that are not yet on film.", author: "Andrei Tarkovsky", author_title: "Russian Film Director", domain: "film", sub_domain: "art cinema", era: "modern", source: "Sculpting in Time", themes: ["vision","possibility","cinema"], archetype_affinity: ["creator","mystic"] },
  { text: "Art is born of an ill-digested childhood.", author: "Andrei Tarkovsky", author_title: "Russian Film Director", domain: "film", sub_domain: "art cinema", era: "modern", source: "Sculpting in Time", themes: ["art","childhood","origin"], archetype_affinity: ["creator","mystic"] },

  // ── TECHNOLOGY ───────────────────────────────────────────────────────────────
  { text: "A ship in port is safe, but that's not what ships are built for.", author: "Grace Hopper", author_title: "American Computer Scientist & US Navy Admiral", domain: "technology", sub_domain: "computer science", era: "modern", themes: ["risk","safety","purpose"], archetype_affinity: ["hero","explorer"] },
  { text: "The most dangerous phrase in the language is: we have always done it this way.", author: "Grace Hopper", author_title: "American Computer Scientist & US Navy Admiral", domain: "technology", sub_domain: "computer science", era: "modern", themes: ["change","tradition","innovation"], archetype_affinity: ["rebel","creator"] },

  { text: "The medium is the message.", author: "Marshall McLuhan", author_title: "Canadian Media Theorist", domain: "technology", sub_domain: "media theory", era: "modern", source: "Understanding Media", themes: ["media","message","form"], archetype_affinity: ["sage","explorer"] },
  { text: "We shape our tools and thereafter our tools shape us.", author: "Marshall McLuhan", author_title: "Canadian Media Theorist", domain: "technology", sub_domain: "media theory", era: "modern", themes: ["tools","shaping","technology"], archetype_affinity: ["sage","creator"] },

  { text: "Think different.", author: "Steve Jobs", author_title: "Co-Founder of Apple Inc.", domain: "technology", sub_domain: "design", era: "contemporary", themes: ["thinking","difference","innovation"], archetype_affinity: ["creator","rebel"] },
  { text: "We are stuck with technology when what we really want is just stuff that works.", author: "Douglas Adams", author_title: "British Author", domain: "technology", sub_domain: "fiction", era: "contemporary", source: "The Salmon of Doubt", themes: ["technology","simplicity","humor"], archetype_affinity: ["rebel","creator"] },

  // ── SPORT ────────────────────────────────────────────────────────────────────
  { text: "Float like a butterfly, sting like a bee.", author: "Muhammad Ali", author_title: "American Professional Boxer & Activist", domain: "sport", sub_domain: "boxing", era: "contemporary", themes: ["grace","power","agility"], archetype_affinity: ["hero","creator"] },
  { text: "It's not bragging if you can back it up.", author: "Muhammad Ali", author_title: "American Professional Boxer & Activist", domain: "sport", sub_domain: "boxing", era: "contemporary", themes: ["confidence","delivery","truth"], archetype_affinity: ["hero","rebel"] },
  { text: "Impossible is just a big word thrown around by small men who find it easier to live in the world they have been given than to explore the power they have to change it.", author: "Muhammad Ali", author_title: "American Professional Boxer & Activist", domain: "sport", sub_domain: "boxing", era: "contemporary", themes: ["possibility","power","change"], archetype_affinity: ["hero","rebel"] },

  { text: "You have to expect things of yourself before you can do them.", author: "Michael Jordan", author_title: "American Professional Basketball Player", domain: "sport", sub_domain: "basketball", era: "contemporary", themes: ["expectation","belief","achievement"], archetype_affinity: ["hero","creator"] },
  { text: "I can accept failure, everyone fails at something. But I cannot accept not trying.", author: "Michael Jordan", author_title: "American Professional Basketball Player", domain: "sport", sub_domain: "basketball", era: "contemporary", themes: ["failure","trying","acceptance"], archetype_affinity: ["hero","explorer"] },

  { text: "The most important thing is to try and inspire people so that they can be great in whatever they want to do.", author: "Kobe Bryant", author_title: "American Professional Basketball Player", domain: "sport", sub_domain: "basketball", era: "contemporary", themes: ["inspiration","greatness","motivation"], archetype_affinity: ["hero","caregiver"] },
  { text: "Great things come from hard work and perseverance. No excuses.", author: "Kobe Bryant", author_title: "American Professional Basketball Player", domain: "sport", sub_domain: "basketball", era: "contemporary", themes: ["hard-work","perseverance","discipline"], archetype_affinity: ["hero","creator"] },
  { text: "The moment you give up is the moment you let someone else win.", author: "Kobe Bryant", author_title: "American Professional Basketball Player", domain: "sport", sub_domain: "basketball", era: "contemporary", themes: ["persistence","competition","will"], archetype_affinity: ["hero","rebel"] },

  // ── HUMOR & WIT ──────────────────────────────────────────────────────────────
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde", author_title: "Irish Playwright & Poet", domain: "literature", sub_domain: "wit", era: "modern", themes: ["authenticity","identity","individuality"], archetype_affinity: ["rebel","creator"] },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde", author_title: "Irish Playwright & Poet", domain: "literature", sub_domain: "wit", era: "modern", source: "The Soul of Man Under Socialism", themes: ["living","existence","rarity"], archetype_affinity: ["rebel","explorer"] },
  { text: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde", author_title: "Irish Playwright & Poet", domain: "literature", sub_domain: "wit", era: "modern", themes: ["forgiveness","enemies","wit"], archetype_affinity: ["rebel","lover"] },
  { text: "I can resist everything except temptation.", author: "Oscar Wilde", author_title: "Irish Playwright & Poet", domain: "literature", sub_domain: "wit", era: "modern", source: "Lady Windermere's Fan", themes: ["temptation","will","honesty"], archetype_affinity: ["rebel","lover"] },

  { text: "The secret of getting ahead is getting started.", author: "Mark Twain", author_title: "American Humorist & Novelist", domain: "literature", sub_domain: "satire", era: "modern", themes: ["action","beginning","momentum"], archetype_affinity: ["hero","explorer"] },
  { text: "Kindness is the language which the deaf can hear and the blind can see.", author: "Mark Twain", author_title: "American Humorist & Novelist", domain: "literature", sub_domain: "satire", era: "modern", themes: ["kindness","language","connection"], archetype_affinity: ["caregiver","lover"] },
  { text: "Travel is fatal to prejudice, bigotry, and narrow-mindedness.", author: "Mark Twain", author_title: "American Humorist & Novelist", domain: "literature", sub_domain: "satire", era: "modern", source: "The Innocents Abroad", themes: ["travel","perspective","open-mindedness"], archetype_affinity: ["explorer","rebel"] },
];

async function main() {
  const rows = cards.map((c) => ({
    id: id(c.author, c.text),
    ...c,
    quality_score: 0,
  }));

  console.log(`Inserting ${rows.length} cards into specimen_cards...`);

  const BATCH = 50;
  let total = 0;

  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH);
    const { data, error } = await supabase
      .from('specimen_cards')
      .upsert(batch, { onConflict: 'id', ignoreDuplicates: true })
      .select('id');

    if (error) {
      console.error(`Batch ${i / BATCH + 1} error:`, error.message);
    } else {
      total += data?.length ?? 0;
      console.log(`Batch ${i / BATCH + 1}: ${data?.length ?? 0} inserted`);
    }
  }

  console.log(`\nDone. ${total} new cards inserted.`);

  const { count } = await supabase
    .from('specimen_cards')
    .select('*', { count: 'exact', head: true });
  console.log(`Total cards in DB: ${count}`);
}

main().catch(console.error);
